Добавляет возможность узнать какую аудиозапись слушает сейчас юзер
OpenVK/openvk pull request #1048
Opened 2023-11-27 22:59 UTC by zavsc

Комментарии излишне, единственно нужно проверить пр)

2023-11-28 10:41 UTC, celestora commented
ты это вообще тестировал?

2023-11-28 10:43 UTC, celestora commented
![image](https://github.com/openvk/openvk/assets/34442450/3618da0b-1d9e-4015-b541-4768a19caf46)

2023-11-28 11:27 UTC, damirap2020 commented
нет, он это не тестировал, на его инстансе не работает музыка

2023-11-28 11:33 UTC, celestora requested changes
![IMG_20231127_205759_405](https://github.com/openvk/openvk/assets/34442450/e3b660e1-e751-4a26-9b53-b28b44cd3539)

2023-11-28 11:33 UTC, celestora commented on VKAPI/Handlers/Account.php
> +            "audio_status"     => is_null($this->getUser()->getCurrentAudioStatus()) ? '' : $this->getUser()->getCurrentAudioStatus(),
В правую часть выражения стоит добавить преобразование в структуру ВК апи. Как это сделать можно посмотреть в файле аудио.пхп

2023-11-28 13:17 UTC, zavolo commented on VKAPI/Handlers/Account.php
> +            "audio_status"     => is_null($this->getUser()->getCurrentAudioStatus()) ? '' : $this->getUser()->getCurrentAudioStatus(),
Всм, можно подробнее

2023-11-28 13:35 UTC, zavsc reviewed
toVkApiStruct

2023-11-29 12:12 UTC, celestora approved these changes
вроде норм

2023-12-02 17:06 UTC, merged