Create es.se
openvk/openvk pull request #257
Opened 2021-10-30 13:39 UTC by evgenyasamur

2021-10-30 13:39 UTC, veselcraft commented
?

2021-10-30 13:39 UTC, dsrev commented
А зачем нам пустой файл?

2021-10-30 13:40 UTC, TAB-q commented
Крутое изменение

2021-10-30 13:41 UTC, l-lacker commented
Зачем

2021-10-30 13:42 UTC, zavsc commented
@evgenyasamur Зачем?

2021-10-30 13:59 UTC, celestora approved these changes
cool and good

2021-10-30 14:00 UTC, veselcraft approved these changes
this is cool but idk it is necessary or not

2021-10-30 14:01 UTC, WerySkok requested changes
Смысл в этом?

2021-11-02 15:13 UTC, dsrev reviewed
h

2021-11-02 19:46 UTC, closed without merging