Users: Add two-factor authentication
OpenVK/openvk pull request #321
Opened 2021-11-29 18:23 UTC by maksalees

# Summary
This PR adds full TOTP 2FA. And even backup codes modeled on the original VK
# Screenshots
![image](https://user-images.githubusercontent.com/50026114/143921986-e49861c6-c4d7-49e8-ac52-2f43865d48a8.png)
![image](https://user-images.githubusercontent.com/50026114/143922029-f3663226-bf20-47e8-b2d1-727d27d082b5.png)
![image](https://user-images.githubusercontent.com/50026114/143922112-d80a1cc5-e49b-461c-b06c-02cc8a02f97e.png)
![image](https://user-images.githubusercontent.com/50026114/143922136-b5eb3676-9645-49bd-9b28-18c7b96134bc.png)
![image](https://user-images.githubusercontent.com/50026114/143922156-73339888-0cb0-46c9-86f0-74e248354eee.png)
![image](https://user-images.githubusercontent.com/50026114/143922186-cff37ee3-cd92-44d5-844d-16e7d66a70bc.png)
![image](https://user-images.githubusercontent.com/50026114/143922218-6508e7d6-173c-4b6d-a38e-def8b68508d8.png)

2021-11-29 18:25 UTC, WerySkok commented
Ура, рабочая альтернатива вместо платной идеи использовать настоящие смс для входа. Они как-то вместе согласуются?

2021-11-29 18:26 UTC, veselcraft commented
НИХУЯ ТЫ УМНЫЙ

2021-11-29 18:27 UTC, veselcraft approved these changes
блятьи да тут даже код смотреть не надо тут всё пиздато

2021-11-29 18:28 UTC, maksalees commented
> Ура, рабочая альтернатива вместо платной идеи использовать настоящие смс для входа. Они как-то вместе согласуются?

Вполне можно в будующем добавить оба метода двухфакторной аутентификации одновременно, как это реализовано в оригинальном ВК. Или ты не про это?

2021-11-29 18:30 UTC, kirpoartur commented
@maksalees они - опора нашего общества. благодаря именно им мы живём в спокойствии и гармонии

2021-11-29 18:33 UTC, WerySkok commented
> Или ты не про это?

В коде уже есть поддержка Zadarma, которая криво работает. Лично я бы давно её вырезал и реализовал бы нормально, но это лучше тебе решать, но это надо как-то обыграть в этом пр.

2021-11-29 18:36 UTC, maksalees commented
> > Или ты не про это?
> 
> В коде уже есть поддержка Zadarma, которая криво работает. Лично я бы давно её вырезал и реализовал бы нормально, но это лучше тебе решать, но это надо как-то обыграть в этом пр.

Думаю это лучше делать в другом PR или коммите, потому что этот просто реализует двухфакторку через TOTP. А еще мне кажется что двухфакторку через SMS лучше вообще не добавлять так как это не безопасно (SIM карту можно легко перевыпустить)

2021-11-29 18:37 UTC, veselcraft commented
https://user-images.githubusercontent.com/22993408/143923969-e0aae418-69d7-439f-a1e2-582d5c74ada4.mp4

2021-11-29 19:03 UTC, zavsc commented
> default.mp4

когда посмотрел исходные коды OpenVK Classic

2021-11-29 19:59 UTC, celestora commented
> > Или ты не про это?
> 
> В коде уже есть поддержка Zadarma, которая криво работает. Лично я бы давно её вырезал и реализовал бы нормально, но это лучше тебе решать, но это надо как-то обыграть в этом пр.

Поддержки задармы нет уже лет 5, там смсц интеграция

2021-11-29 20:34 UTC, celestora requested changes
Некоторые строки не переведены, но для OpenVK это нормально.
Фича впринципе готова и реализована круто, однако хотелось бы более причёсанный код в некоторых местах и раставленные индексы в SQL, а то при большом кол-ве резервных кодов 2fa-вход будет лагать.

2021-11-29 20:34 UTC, celestora commented on Web/Models/Entities/User.php
> +        }
можно убрать `{ ... }`

2021-11-29 20:34 UTC, celestora commented on Web/Models/Entities/User.php
> +                code => random_int(10000000, 99999999)
для таких вещей овк обычно использует повсеместно `openssl_random_pseudo_bytes`

2021-11-29 20:34 UTC, celestora commented on Web/Presenters/AuthPresenter.php
> +                if(!($twoFactorAuthCode === (new Totp)->GenerateToken(Base32::decode($twoFactorAuthSecret)) || (new User($user->related("profiles.user")->fetch()))->use2faBackupCode((int) $twoFactorA
имхо строчка слишком длинная
мб сократить как-то?

2021-11-29 20:34 UTC, celestora commented on Web/Presenters/templates/Auth/LoginSecondFactor.xml
> +                        <span>{_"code"}: </span>
Можно просто `{_code}`

2021-11-29 20:34 UTC, celestora commented on install/sqls/00013-2fa.sql
> +    `code` int unsigned NOT NULL
добавить нужно индекс на овнера и составной code+owner

2021-11-29 20:38 UTC, celestora commented on Web/Presenters/AuthPresenter.php
> +use lfkeitel\phptotp\{Base32,Totp};
А ещё тут пробел можно

2021-11-29 20:39 UTC, maksalees commented on Web/Models/Entities/User.php
> +                code => random_int(10000000, 99999999)
Но `random_int` же тоже криптографически безопасен. Ну ладно

2021-11-29 20:39 UTC, celestora commented on Web/Presenters/UserPresenter.php
> +            exit;
Chandler::MVC::SimplePresenter::redirect

2021-11-29 21:09 UTC, maksalees commented on Web/Models/Entities/User.php
> +                code => random_int(10000000, 99999999)
`openssl_random_pseudo_bytes` возвращает случайные байты, которые потом можно конвериторовать в HEX с помощью `bin2hex`. Таким образом получится строка в которой будут и цифры и буквы. Наверное есть другая функция, которая может конвертировать байты в десятичное число просто, но я такой не нашел. В любом случае будет больше кода чем просто с `random_int`. Мне кажется лучше просто оставить `random_int` и не городить велосипеды, учитывая что он и так криптографически сильный

2021-11-29 21:25 UTC, maksalees commented on install/sqls/00013-2fa.sql
> +    `code` int unsigned NOT NULL
```sql
ALTER TABLE `2fa_backup_codes`
  ADD KEY `code` (`code`,`owner`),
  ADD KEY `FK_ownerToCode` (`owner`);
```
Правильно?

2021-11-29 21:29 UTC, maksalees commented on Web/Presenters/AuthPresenter.php
> +                if(!($twoFactorAuthCode === (new Totp)->GenerateToken(Base32::decode($twoFactorAuthSecret)) || (new User($user->related("profiles.user")->fetch()))->use2faBackupCode((int) $twoFactorA
```php
$ovkUser = (new User($user->related("profiles.user")->fetch()));
if(!($code === (new Totp)->GenerateToken(Base32::decode($secret)) || $ovkUser->use2faBackupCode((int) $code))) {
```
Укоротил название переменных и вынес получение пользователя в отдельную переменную. Сойдет?

2021-11-30 07:28 UTC, dsrev approved these changes

2021-11-30 15:03 UTC, maksalees commented
@celestora :3

2021-11-30 15:05 UTC, celestora commented
@maksalees ?

2021-11-30 15:06 UTC, veselcraft commented
@celestora !

2021-11-30 15:06 UTC, maksalees commented
> @maksalees ?

Посмотри на код ревью

2021-11-30 15:22 UTC, celestora commented on Web/Models/Entities/User.php
> +                code => random_int(10000000, 99999999)
Как-то вы плохо искали: `(int) bindec(…)`

2021-11-30 15:22 UTC, celestora commented on Web/Presenters/AuthPresenter.php
> +                if(!($twoFactorAuthCode === (new Totp)->GenerateToken(Base32::decode($twoFactorAuthSecret)) || (new User($user->related("profiles.user")->fetch()))->use2faBackupCode((int) $twoFactorA
Убрать лишние скобки и будет круто

2021-11-30 15:23 UTC, celestora commented on install/sqls/00013-2fa.sql
> +    `code` int unsigned NOT NULL
Да

2021-11-30 15:23 UTC, celestora commented
> > @maksalees ?
> 
> Посмотри на код ревью и ответь на вопросы

Готово

2021-11-30 15:40 UTC, maksalees commented on Web/Models/Entities/User.php
> +                code => random_int(10000000, 99999999)
@celestora Как-то плохо оно работает...
![image](https://user-images.githubusercontent.com/50026114/144078605-6f3bcffb-92a8-44a0-9ddb-39e992c10ffe.png)
А теперь посмотрим пример использования
![image](https://user-images.githubusercontent.com/50026114/144077536-57d6500d-4d44-4890-a5f2-9c9b3d48eb4d.png)
Конечно можно наколхозить конвертацию результата `openssl_random_pseudo_bytes` в строку которую хочет `bindec`, но зачем если просто можно использовать `random_int`?

2021-11-30 15:42 UTC, maksalees commented on Web/Presenters/AuthPresenter.php
> +                if(!($twoFactorAuthCode === (new Totp)->GenerateToken(Base32::decode($twoFactorAuthSecret)) || (new User($user->related("profiles.user")->fetch()))->use2faBackupCode((int) $twoFactorA
Полный вариант if:
```php
$ovkUser = (new User($user->related("profiles.user")->fetch()));
if(!($code === (new Totp)->GenerateToken(Base32::decode($secret)) || $ovkUser->use2faBackupCode((int) $code))) {
    $this->flash("err", "Не удалось войти", "Неверный код двухфакторной аутентификации");
    return;
}
```
Вы предлагаете сделать так?
```php
$ovkUser = (new User($user->related("profiles.user")->fetch()));
if(!($code === (new Totp)->GenerateToken(Base32::decode($secret)) || $ovkUser->use2faBackupCode((int) $code)))
    $this->flash("err", "Не удалось войти", "Неверный код двухфакторной аутентификации"); return;
```
`flashFail` здесь использовать не выйдет

2021-11-30 16:08 UTC, celestora commented on Web/Presenters/AuthPresenter.php
> +                if(!($twoFactorAuthCode === (new Totp)->GenerateToken(Base32::decode($twoFactorAuthSecret)) || (new User($user->related("profiles.user")->fetch()))->use2faBackupCode((int) $twoFactorA
Нет, с { всё ок, я про:
`$ovkUser = (new User($user->related("profiles.user")->fetch()));` -> `$ovkUser = new User($user->related("profiles.user")->fetch());`

2021-11-30 16:09 UTC, maksalees commented on Web/Presenters/AuthPresenter.php
> +                if(!($twoFactorAuthCode === (new Totp)->GenerateToken(Base32::decode($twoFactorAuthSecret)) || (new User($user->related("profiles.user")->fetch()))->use2faBackupCode((int) $twoFactorA
А xd

2021-11-30 16:09 UTC, celestora commented on Web/Models/Entities/User.php
> +                code => random_int(10000000, 99999999)
> Конечно можно наколхозить конвертацию результата openssl_random_pseudo_bytes в строку которую хочет bindec

Прошу прощения я [[BIG SHOT]]. `hexdec` правильная функция.

2021-11-30 16:30 UTC, maksalees commented on Web/Models/Entities/User.php
> +                code => random_int(10000000, 99999999)
@celestora Для получения числа длинной ровно 8 цифр наколхозил такой код:
```php
(int) substr((string) hexdec(bin2hex(openssl_random_pseudo_bytes(4))), 0, 8)
```
Наверное можно обрезать число до 8 цифр другим способ, но этот самый простой. Использовать это или все таки оставляем `random_int`?

2021-11-30 16:44 UTC, HSDChannel commented
блин
идея реально прикольная

2021-11-30 16:44 UTC, maksalees commented
> блин идея реально прикольная

Это не только идея, это ее реализация

2021-11-30 16:57 UTC, celestora commented
@HSDChannel С такой грустью говоришь, будто реализации нет

2021-11-30 17:17 UTC, HSDChannel commented
> > блин идея реально прикольная
> 
> Это не только идея, это ее реализация

ну я это и имел в виду

2021-11-30 17:51 UTC, celestora commented on Web/Models/Entities/User.php
> +                code => random_int(10000000, 99999999)
Ладно random_int

2021-11-30 17:57 UTC, maksalees commented
@celestora Я внес все изменения. Могу ли я теперь замерджить?

2021-12-01 15:13 UTC, veselcraft requested changes
Нужно локализировать пару строк, а так норм

2021-12-01 15:13 UTC, veselcraft commented on composer.json
> +        "scssphp/scssphp": "dev-master",
кстати а зачем нам scss

2021-12-01 15:13 UTC, veselcraft commented on Web/Models/Entities/User.php
> +                code => random_int(10000000, 99999999)
для безопасности всё таки стоит выбрать вариант с `openssl_random_pseudo_bytes`. чем больше символов используется - тем безопаснее, имхо

2021-12-01 15:13 UTC, veselcraft commented on Web/Models/Entities/User.php
> +                code => random_int(10000000, 99999999)
ору

2021-12-01 15:13 UTC, veselcraft commented on Web/Presenters/UserPresenter.php
> +                                $this->flashFail("err", "Ошибка", "Неверный код двухфакторной аутентификации");
лучше все это дело локализировать

2021-12-01 15:13 UTC, veselcraft commented on Web/Presenters/VKAPIPresenter.php
> +            $this->fail(28, "Invalid 2FA code", "internal", "acquireToken");
локализовать

2021-12-01 15:13 UTC, veselcraft commented on Web/Presenters/templates/Auth/FinishRestoringPassword.xml
> +            <label for="code">Код двухфакторной аутентификации: </label>
локализовать

2021-12-01 15:13 UTC, maksalees commented on Web/Presenters/VKAPIPresenter.php
> +            $this->fail(28, "Invalid 2FA code", "internal", "acquireToken");
Так это API, его не нужно локализовывать

2021-12-01 15:14 UTC, maksalees commented on Web/Presenters/templates/Auth/FinishRestoringPassword.xml
> +            <label for="code">Код двухфакторной аутентификации: </label>
Это лучше локализовывать вместе со всей страницей восстановления пароля, а это не тема этого PR

2021-12-01 15:14 UTC, maksalees commented on composer.json
> +        "scssphp/scssphp": "dev-master",
Хз

2021-12-01 15:15 UTC, veselcraft commented on Web/Presenters/VKAPIPresenter.php
> +            $this->fail(28, "Invalid 2FA code", "internal", "acquireToken");
тогда извиняюсь

2021-12-01 15:15 UTC, veselcraft commented on Web/Presenters/templates/Auth/FinishRestoringPassword.xml
> +            <label for="code">Код двухфакторной аутентификации: </label>
после merge тогда локализируем это дело

2021-12-01 15:18 UTC, maksalees commented on Web/Models/Entities/User.php
> +                code => random_int(10000000, 99999999)
> для безопасности всё таки стоит выбрать вариант с openssl_random_pseudo_bytes. чем больше символов используется - тем безопаснее, имхо

Да, но OpenVK косплеит оригинальный ВК который по каким то причинам в резервных кодах использует только цифры

2021-12-01 16:04 UTC, maksalees commented on Web/Presenters/UserPresenter.php
> +                                $this->flashFail("err", "Ошибка", "Неверный код двухфакторной аутентификации");
Готово

2021-12-01 18:04 UTC, maksalees commented
@veselcraft Ну вроде все сделал

2021-12-01 18:15 UTC, veselcraft requested changes
там ещё кое че есть но а так

https://user-images.githubusercontent.com/22993408/144290299-1f1dbc2a-3fc9-45d1-bb08-f8491023b2bf.mp4

2021-12-01 18:15 UTC, veselcraft commented on Web/Presenters/AuthPresenter.php
>              $this->flash("err", "Ошибка манипулирования токеном", "Токен недействителен или истёк");
а тут?

2021-12-01 18:16 UTC, maksalees commented on Web/Presenters/AuthPresenter.php
>              $this->flash("err", "Ошибка манипулирования токеном", "Токен недействителен или истёк");
М? Этот код был и до моего PR

2021-12-01 18:23 UTC, veselcraft commented
так, ну впринципе я удовлетворён (единственное кое че измени), осталось дождаться @celestora

2021-12-01 18:24 UTC, maksalees commented on Web/Presenters/AuthPresenter.php
>              $this->flash("err", "Ошибка манипулирования токеном", "Токен недействителен или истёк");
Сообщение ниже переведено уже

2021-12-01 18:24 UTC, maksalees commented
> так, ну впринципе я удовлетворён (единственное кое че измени), осталось дождаться @celestora

Че изменить?)

2021-12-01 18:47 UTC, veselcraft approved these changes
https://user-images.githubusercontent.com/22993408/144294999-1f09cbec-4b34-43a4-b711-ce10beaf241d.mp4

2021-12-02 15:31 UTC, celestora approved these changes

2021-12-02 15:31 UTC, merged

2021-12-02 15:36 UTC, veselcraft commented
https://user-images.githubusercontent.com/22993408/144453260-3d9902cd-1fac-48f0-88ac-a3a8de25af12.mp4

2021-12-02 15:37 UTC, dsrev commented
@veselcraft ХАПЪАХРЪАХЪПЪХХАЪП