Esperanto localization
OpenVK/openvk pull request #338
Opened 2021-12-11 20:03 UTC by n1rwana

2021-12-11 20:09 UTC, maksalees commented
Not all strings have been translated in this translation. Can you translate in full? Thank you.

2021-12-11 20:21 UTC, veselcraft requested changes
https://user-images.githubusercontent.com/22993408/145690527-d743a294-db87-4e43-bd4f-4fc8e9f9f58c.mp4

2021-12-11 20:21 UTC, veselcraft commented on locales/eo.strings
> +"__locale" = "eo_EO.utf8;eo_EO.UTF-8;Esp";
`eo.utf8` is correct

2021-12-11 20:21 UTC, veselcraft commented on locales/eo.strings
> +"__WinEncoding" = "Windows-1251";
wtf??

2021-12-11 20:21 UTC, veselcraft commented on locales/eo.strings
> +"save" = "Savi";
`konservi` is correct

2021-12-11 20:21 UTC, veselcraft commented on locales/eo.strings
> +"years_other" = "$1 jaroj malnova";
just `jara` is ok

2021-12-11 20:21 UTC, veselcraft commented on locales/eo.strings
> +"politViews_7" = "Monarchical";
`monarĥo`

2021-12-11 20:21 UTC, veselcraft commented on locales/eo.strings
> +"address" = "Address";
why this wasn't translated?

2021-12-11 20:21 UTC, veselcraft commented on locales/eo.strings
> +"version_incompatibility" = "Ĉi tiu aldonaĵo ne povis esti montrata. Verŝajne la datumbazo estas nekongrua kun la nuna versio de OpenVK.";
`de la`

2021-12-11 20:21 UTC, veselcraft commented on locales/eo.strings
> +"upload_button" = "Alŝutu";
`Alŝuti`

2021-12-11 20:21 UTC, veselcraft commented on locales/eo.strings
> +"edit_button" = "redakti";
check 263 line

2021-12-11 20:21 UTC, veselcraft commented on locales/eo.strings
> +"paginator_next" = "Venonta";
not needed cos deprecated

2021-12-11 20:21 UTC, veselcraft commented on locales/list.yml
> +    native_name: "Эсперанто"
native name is the native name of language (for example the native name of kazakh language is Қазақша)

2021-12-12 09:11 UTC, maksalees commented
Еще не все строки переведены

2021-12-12 09:13 UTC, veselcraft requested changes

2021-12-12 09:13 UTC, veselcraft commented on locales/eo.strings
>  "ok" = "OK";
`Bone`

2021-12-12 20:25 UTC, merged