New feature: users can rate support answers
OpenVK/openvk pull request #342
Opened 2021-12-12 18:15 UTC by n1rwana

In this feature users will be able to rate support answers. They will see links **"This is good answer"** and **"This is bad answer"**, like it was in original VK. Also support agents can see, what marks got their answers.

### How the user sees it:
![user_view](https://user-images.githubusercontent.com/93197434/145724317-f4621c85-559f-4c93-b25e-23cecd68528b.png)

### How the agent sees it:
![agent_view](https://user-images.githubusercontent.com/93197434/145724330-6050d760-143a-40e0-a3b4-81269d3126a7.png)

2021-12-12 18:25 UTC, MatroCholo commented
@n1rwana Ого

2021-12-12 18:27 UTC, veselcraft requested changes
Сама по себе фича прикольная и рабочая, но есть пару моментов, которые желательно бы пофиксить

2021-12-12 18:27 UTC, veselcraft commented on Web/Presenters/SupportPresenter.php
> +    function renderRateAnswerBad(int $id): void
Функции `renderRateAnswerBad` и `renderRateAnswerGood` можно без всяких последствий объединить

2021-12-12 18:27 UTC, veselcraft commented on Web/Presenters/templates/Support/AnswerTicket.xml
> +               {/if}
Тут тоже можно упростить:
```php
{ifset $comment->getMark()}
<div class="post-menu">
 <strong>
  {if $comment->getMark() === 1}
   {_support_good_answer_agent}
  {elseif $comment->getMark() === 2}
   {_support_bad_answer_agent}
  {/if}
 </strong>
</div>
{/if}
```

2021-12-12 18:27 UTC, veselcraft commented on Web/Presenters/templates/Support/View.xml
> +                  <a href="/support/comment/{$comment->getId()}/rateGood">{_support_rate_good_answer}}</a>
Не обязательно, но я бы к такой фиче прикрутил Ajax

2021-12-12 18:27 UTC, veselcraft commented on Web/Presenters/templates/Support/View.xml
> +                {/if}
*смотри комментарий про упрощение*

2021-12-12 18:27 UTC, veselcraft commented on locales/ru.strings
> +
А где строчки для аглицкого языка?

2021-12-12 18:30 UTC, maksalees requested changes
Все хорошо, но есть пара моментов

2021-12-12 18:30 UTC, maksalees commented on Web/Models/Repositories/TicketComments.php
> +        $comm = $this->comments->where(['id' => $id])->fetch();
Почему бы не назвать эту переменную `$comment`?

2021-12-12 18:30 UTC, maksalees commented on Web/Presenters/SupportPresenter.php
> +        if ($this->user->id === $this->tickets->get($comment->getTicketId()->getUser()->getId())) {
Согласно стилю кода OpenVK эта строка и все другие `if` должны выглядить так:
```php
if($this->user->id === $this->tickets->get($comment->getTicketId()->getUser()->getId())) {
```

2021-12-12 18:30 UTC, maksalees commented on Web/Presenters/SupportPresenter.php
> +            $this->flashFail("succ", "Успешно", "Вы оставили положительный отзыв об ответе");
Это не помешало бы перевести

2021-12-12 18:30 UTC, maksalees commented on Web/Presenters/templates/Support/AnswerTicket.xml
> +                    {if $comment->getMark() === 1}
Тут не помешали бы нормальные отступы

2021-12-12 18:30 UTC, maksalees commented on Web/Presenters/templates/Support/View.xml
> +               {if $comment->getUType() === 1 && $comment->getMark() === 0}
Пожалуйста, сделайте нормальные отступы

2021-12-12 18:30 UTC, maksalees commented on Web/Presenters/SupportPresenter.php
> +            $this->flashFail("err", "Ошибка", "Ошибка доступа");
Это тоже

2021-12-12 18:30 UTC, maksalees commented on Web/Models/Repositories/TicketComments.php
> +    // We can get comment by it's ID using this function
Используйте PHPDoc, чтобы IDE отображи комментарий к методу:
```php
/**
 * Get comment by it's ID
/*
```
Также из названия метода и так легко можно понять что он делает, так что этот комментарий не нужен

2021-12-12 18:41 UTC, veselcraft commented on Web/Presenters/SupportPresenter.php
> +        if ($this->user->id === $this->tickets->get($comment->getTicketId()->getUser()->getId())) {
Минуту в глаза долбился, не понимал в чем разница...

2021-12-12 18:41 UTC, veselcraft commented on Web/Presenters/SupportPresenter.php
> +            $this->flashFail("succ", "Успешно", "Вы оставили положительный отзыв об ответе");
Через функцию `tr`!

2021-12-12 20:24 UTC, zavsc commented
@n1rwana прикольно

2021-12-12 22:06 UTC, maksalees requested changes

2021-12-12 22:06 UTC, maksalees commented on Web/Presenters/SupportPresenter.php
> +        if ($this->user->id === $this->tickets->get($comment->getTicketId())->getUser()->getId()) {
Я же писал, ifы делать надо по другому:
```php
if($this->user->id === $this->tickets->get($comment->getTicketId())->getUser()->getId()) {
```

2021-12-12 22:06 UTC, maksalees requested changes

2021-12-12 22:06 UTC, maksalees commented on Web/Presenters/templates/Support/View.xml
> +    location.reload();
Ебать AJAX с перезагрузкой страницы XD

2021-12-13 10:30 UTC, veselcraft commented on Web/Presenters/templates/Support/View.xml
> +    location.reload();
ААХАХАХАХАХАХ

2021-12-13 10:34 UTC, veselcraft requested changes
https://user-images.githubusercontent.com/22993408/145796751-c4db6053-11ba-43f5-a9af-ba76b5226da6.mp4

2021-12-13 10:34 UTC, veselcraft commented on Web/Presenters/SupportPresenter.php
> +        if ($this->user->id === $this->tickets->get($comment->getTicketId())->getUser()->getId()) {
tl;dr: не надо ставить пробел между `if` и скобкой

2021-12-13 10:34 UTC, veselcraft commented on Web/Presenters/templates/Support/AnswerTicket.xml
> +                        {if $comment->getMark() != null}
`{if $comment->getUType() === 1 && $comment->getMark() != null}`

2021-12-13 10:34 UTC, veselcraft commented on Web/Presenters/templates/Support/View.xml
> +                  {if $comment->getMark() != null}
`{if $comment->getUType() === 1 && $comment->getMark() != null}`

2021-12-13 13:08 UTC, maksalees requested changes

2021-12-13 13:08 UTC, maksalees commented on Web/Presenters/templates/Support/View.xml
> +<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
jQuery уже используется, его не нужно добавлять

2021-12-13 13:12 UTC, maksalees approved these changes

2021-12-14 11:19 UTC, veselcraft approved these changes
👌

2021-12-14 11:19 UTC, veselcraft commented on Web/Presenters/templates/Support/View.xml
> +  }
Другое дело :DDD

2021-12-14 11:32 UTC, celestora requested changes
Свои придирки оставила, но больше всего меня волнует то, что у вас используется tinyint (спасибо, что экономите память и выбираете нужный тип по размеру), хотя здесь большее подойдёт BOOLEAN DEFAULT NULL (0 - нет лайка, 1 - лайкнули, null - нет оценки). Так имхо логичнее и можно ещё сэкономить места :D
Ну и циферки в шаблонах выглядят как магические числа, не понятно сразу, что они значат :3
Конеч последнее больше придика, но мне бы реально зашло бы больше если бы метод у модели был `isLikedByUser(): ?bool`.

2021-12-14 11:32 UTC, celestora commented on locales/en.strings
> +"support_bad_answer_user" = "You have left a negative feedback.";
have лишний

2021-12-14 11:32 UTC, celestora commented on locales/en.strings
> +"support_rated_bad" = "You have left a negative feedback about the answer.";
have лишний

2021-12-14 11:32 UTC, celestora commented on install/sqls/00014-helpdesk-answers-evaluvating.sql
> +ALTER TABLE `tickets_comments` ADD `mark` TINYINT NOT NULL DEFAULT '0';
не было бы логичнее использовать boolean?

2021-12-14 11:32 UTC, celestora commented on Web/routes.yml
> +      handler: "Support->RateAnswer"
По кодстайлу у нас первая буква метода с мелкой пишется

2021-12-14 11:32 UTC, celestora commented on Web/Presenters/SupportPresenter.php
> +        }
Што тут произошло? Отформатируйте пожалуйста код более мило: пробел после else в else if бы...
Ну и табы и пробелы намешаны, не мило, давайте оставим только пробелы и уберём комменты (и неиспользуемые ifы) :D

2021-12-14 14:11 UTC, celestora requested changes
![image](https://user-images.githubusercontent.com/34442450/146014422-f38ec961-8bc1-4c5f-9683-981dc56c4d31.png)

2021-12-14 14:11 UTC, celestora commented on Web/Presenters/templates/Support/AnswerTicket.xml
> +                        {if $comment->isLikedByUser() === true}
зачем это сравнение?

2021-12-14 14:11 UTC, celestora commented on Web/Presenters/templates/Support/AnswerTicket.xml
> +                        {elseif $comment->isLikedByUser() === false}
здесь можно просто `else`

2021-12-14 14:11 UTC, celestora commented on Web/Presenters/templates/Support/View.xml
> +                      {if $comment->isLikedByUser() === true}
сравнение смешное

2021-12-14 14:11 UTC, celestora commented on Web/Presenters/templates/Support/View.xml
> +                      {elseif $comment->isLikedByUser() === false}
`else` можно

2021-12-14 17:25 UTC, celestora requested changes

2021-12-14 17:25 UTC, celestora commented on Web/Models/Entities/TicketComment.php
> +    function getMark(): int
при возврате NULL вылезет `TypeError`, поменяйте возвращаемый тип на `?int`.

2021-12-14 17:25 UTC, celestora commented on Web/Presenters/SupportPresenter.php
> +            }
1) здесь можно убрать `{` у if'ов.
2) точно ли сохранение информации должно быть до проверки?..

2021-12-14 17:25 UTC, celestora commented on Web/Presenters/SupportPresenter.php
> +        if($this->user->id === $this->tickets->get($comment->getTicketId())->getUser()->getId()) {
думаю так будет чуточку красивее:
```php
if($this->user->id !== $this->tickets->get($comment->getTicketId())->getUser()->getId())
    exit(header("HTTP/1.1 403 Forbidden"));
 
 # то, что у вас не в else
 ```

2021-12-14 18:12 UTC, celestora requested changes

2021-12-14 18:12 UTC, celestora commented on Web/Presenters/SupportPresenter.php
> +    }
すごいですね!

2021-12-14 18:12 UTC, celestora commented on Web/Models/Entities/TicketComment.php
> +        }
Можно заменить на `switch`

2021-12-14 18:12 UTC, celestora commented on Web/Models/Repositories/TicketComments.php
> +        $comment = $this->comments->where(['id' => $id])->fetch();
Тут можно `$this->comments->get($id);`

2021-12-14 18:12 UTC, celestora commented on Web/Models/Repositories/TicketComments.php
> +            return null;
В OpenVK null пишется как `NULL`, кроме тех случаев, когда передаётся по ссылке (тогда `nullptr`), здесь `NULL` надо бы.

2021-12-14 18:24 UTC, celestora requested changes

2021-12-14 18:24 UTC, celestora commented on Web/Models/Entities/TicketComment.php
> +                break;
Поч пробелы после значения кейсов?

2021-12-14 18:24 UTC, celestora commented on Web/Models/Entities/TicketComment.php
> +                return null;
Большой `NULL` лучше.

2021-12-14 18:24 UTC, celestora commented on Web/Models/Entities/TicketComment.php
> +        switch ($mark) {
Лучше убрать лишнюю новую строчку и пробел после `switch`.

2021-12-14 22:55 UTC, celestora approved these changes
ок

2021-12-14 22:56 UTC, merged