Groups: Transfer community permissions to another user
OpenVK/openvk pull request #348
Opened 2021-12-15 14:32 UTC by n1rwana

Groups: Transfer community permissions to another user

(Issue #302 )

2021-12-15 14:35 UTC, dsrev commented
А как сюда попал коммит с добавлением "Пригласить" в шапку сайта?

2021-12-15 14:36 UTC, n1rwana commented
`¯\_(ツ)_/¯`

2021-12-15 16:29 UTC, maksalees commented
Я думаю что лучше добавить диалог с подтверждением, так как это действие необратимо.
Также мне кажется что для подобного лучше спрашивать пароль и давать бывшему владельцу админку (он сможет сам с себя ее снять)

2021-12-15 16:31 UTC, maksalees commented on locales/ru.strings
> +"group_owner_setted" = "Новый владелец ($1) успешно назначен в сообщество $2. Если Вы хотите вернуть сообщество, обратитесь в техническую поддержку сайта.";
Почему бы тут не оставить ссылку на поддержку?

2021-12-15 18:58 UTC, maksalees requested changes

2021-12-15 18:58 UTC, maksalees commented on Web/Presenters/templates/Group/Followers.xml
> +                Внимание! Вы передаёте права владельца пользователю {$user->getFullName()}. После передачи Вы получите роль администратора в сообществе.
Предлагаю изменить на "Внимание! Вы передаёте права владельца пользователю {$user->getFullName()}. Это действие необратимо. После передави вы останетесь адмиинстратором, но сможете легко перестать им быть."
Также это надо бы перевести используя функцию `tr` (она работает даже в JavaScript)

2021-12-15 18:58 UTC, maksalees commented on Web/Presenters/GroupPresenter.php
> +use Chandler\Security\Authenticator;
Согласно стилю кода, между `use` и классом должна быть пустая строка

2021-12-15 20:40 UTC, maksalees requested changes

2021-12-15 20:40 UTC, maksalees commented on Web/Presenters/templates/Group/Followers.xml
>                      <label for="password">Пароль</label>
А остальное в диалоговом окне перевести?

2021-12-16 10:43 UTC, maksalees approved these changes

2021-12-16 18:22 UTC, maksalees commented
Думаю можно мерджить

2021-12-16 18:25 UTC, maksalees requested changes
Хотя...

2021-12-16 18:25 UTC, maksalees commented on Web/Presenters/GroupPresenter.php
> +            $this->redirect("/groups".$this->user->id);
Предлагаю заменить на `$this->redirect("/groups" . $this->user->id);`

2021-12-16 18:25 UTC, maksalees commented on Web/Presenters/GroupPresenter.php
> +    function renderChangeOwner(int $id, int $newOwnerID): void
Предлагаю заменить название аргумента `$newOwnerID` на `$newOwnerId`, чтобы оно большое соответствовало остальному коду

2021-12-16 18:38 UTC, maksalees approved these changes

2021-12-16 18:40 UTC, merged

2021-12-16 18:45 UTC, maksalees commented
Блин, при ревью не заметил прикол. А реверт я случайно сделал