Soviet & Udm locales
OpenVK/openvk pull request #380
Opened 2021-12-30 20:39 UTC by themohooks

2021-12-30 20:39 UTC, themohooks commented
Локали пока не полностью готовы, буду обновлять пулл по мере обновления.

2021-12-30 20:40 UTC, maksalees commented on locales/su.strings
> +"friends_add" = "Добавить в друзья";
Мжет изменить тут на "Добавить в товарищи?"

2021-12-30 20:41 UTC, MatroCholo commented
@themohooks Вова будет доволен

2021-12-30 20:44 UTC, themohooks commented on locales/su.strings
> +"friends_add" = "Добавить в друзья";
готово

2021-12-30 21:53 UTC, veselcraft requested changes
Советский неплох, но удмуртский почему-то не до конца, обрывается на сотых строчках.
Алсо, необходимо указать язык и самого себя в файле `list.yml`, иначе он тупо не будет работать 🤷

2021-12-30 21:53 UTC, veselcraft commented on locales/udm.strings
> +"version_incompatibility" = "Не удалось отобразить это вложение. Возможно, база данных несовместима с текущей версией OpenVK.";
а остальное перевести?

2021-12-31 01:36 UTC, themohooks commented on locales/udm.strings
> +"version_incompatibility" = "Не удалось отобразить это вложение. Возможно, база данных несовместима с текущей версией OpenVK.";
исправил

2021-12-31 06:57 UTC, veselcraft commented
Не хватает флагов, забыл сказать.
Удмуртия: ![image](https://user-images.githubusercontent.com/22993408/147808469-6f79322a-8965-4c0f-a621-c59a933abc23.png)
СССР: ![image](https://user-images.githubusercontent.com/22993408/147808547-b00791f9-d0e1-45b0-a327-8ab19083ffa5.png)
Их надо добавить в https://github.com/openvk/openvk/tree/master/Web/static/img/flags

И удмуртский доперевести!

2021-12-31 06:58 UTC, themohooks commented
> Не хватает флагов, забыл сказать.
> Удмуртия: ![image](https://user-images.githubusercontent.com/22993408/147808469-6f79322a-8965-4c0f-a621-c59a933abc23.png)
> СССР: ![image](https://user-images.githubusercontent.com/22993408/147808547-b00791f9-d0e1-45b0-a327-8ab19083ffa5.png)
> Их надо добавить в https://github.com/openvk/openvk/tree/master/Web/static/img/flags
> 
> И удмуртский доперевести!

Домой приеду — допереведу, флаги попробую сам сделать под стиль классического ВК (или взять с веб-архива)

2021-12-31 06:59 UTC, veselcraft commented
>флаги попробую сам сделать под стиль классического ВК (или взять с веб-архива)
Зачем? Это и так адаптированные флаги под стиль

2021-12-31 07:04 UTC, themohooks commented
> >флаги попробую сам сделать под стиль классического ВК (или взять с веб-архива)
> 
> Зачем? Это и так адаптированные флаги под стиль

а)
я думал это у меня такие эмодзи показываются, похожи очень

2021-12-31 07:37 UTC, veselcraft commented
@themohooks ор

2021-12-31 12:53 UTC, themohooks commented
@veselcraft проверяй

2021-12-31 13:02 UTC, veselcraft requested changes
всё ещё не всё переведено (то что явно на русском, но не отдельные слова)

2021-12-31 13:02 UTC, veselcraft commented on locales/udm.strings
> +"video_uploaded" = "Etkileşimli";
почему на латинском лол

2021-12-31 13:02 UTC, veselcraft commented on locales/udm.strings
> +"info_uploaded_by" = "Etkileşimli";
и тут

2021-12-31 13:02 UTC, veselcraft commented on locales/udm.strings
>  "support_new_content" = "Опишите проблему или предложение";
а это

2022-01-06 06:31 UTC, dsrev commented
Прошло 6 дней...

2022-01-06 09:00 UTC, themohooks commented
> Прошло 6 дней...

Вове сообщил, остальным забыл
Я сейчас не дома, пулл закончу 8-10 января(когда я буду дома). Извиняюсь за - задержки

2022-01-09 04:56 UTC, themohooks commented
> > Прошло 6 дней...
> 
> Вове сообщил, остальным забыл
> Я сейчас не дома, пулл закончу 8-10 января(когда я буду дома). Извиняюсь за - задержки

Приветствую, уже в пути домой, приеду в ночь с 9 на 10 января. Вновь извиняюсь за задержки.

2022-01-09 04:57 UTC, dsrev commented
Всё ок.

2022-01-10 07:32 UTC, themohooks commented on locales/udm.strings
>  "support_new_content" = "Опишите проблему или предложение";
исправил

2022-01-10 07:33 UTC, themohooks commented on locales/udm.strings
> +"info_uploaded_by" = "Etkileşimli";
исправил

2022-01-10 07:33 UTC, themohooks commented on locales/udm.strings
> +"video_uploaded" = "Etkileşimli";
исправил

2022-01-10 07:35 UTC, themohooks commented
исправил удмуртские стринги

2022-01-10 07:37 UTC, dsrev commented
![Screenshot_2022-01-10-14-36-58-05_320a9a695de7cdce83ed5281148d6f19.jpg](https://user-images.githubusercontent.com/55238545/148731649-32086507-2001-4792-bc2b-d401b293029d.jpg)

Уверен?

2022-01-10 07:46 UTC, themohooks commented
> Уверен?

исправил

2022-01-19 13:14 UTC, merged