Groups: Update groups layot
OpenVK/openvk pull request #444
Opened 2022-01-30 23:46 UTC by KosFurler

2022-01-30 23:51 UTC, veselcraft requested changes
Проблемы с табами. Огромные. Советую погуглить `Beautifier` в гугле для VS Code

Алсо, было бы неплохо перевести новые приколы и на английский язык

2022-01-30 23:51 UTC, veselcraft commented on Web/Presenters/templates/@listView.xml
> +        {/ifset}
табов не хватает

2022-01-30 23:51 UTC, veselcraft commented on Web/Presenters/templates/@listView.xml
> +        {/ifset}
тут тоже

2022-01-30 23:51 UTC, veselcraft commented on Web/Presenters/templates/User/Groups.xml
> +    {else}
лишний таб

2022-01-30 23:51 UTC, veselcraft commented on Web/Presenters/templates/User/Groups.xml
> +    {/if}
тут тоже

2022-01-30 23:51 UTC, veselcraft commented on Web/Presenters/templates/User/Groups.xml
> +{/block}
табы уебанские

2022-01-30 23:51 UTC, veselcraft commented on Web/Presenters/templates/User/Groups.xml
> +{/block}
каша какая то

2022-01-30 23:51 UTC, veselcraft commented on Web/Presenters/templates/components/error.xml
> +</center>
ну тут ещё ладно)

2022-01-30 23:51 UTC, veselcraft commented on Web/static/css/style.css
> +  }
опять лишние табы

2022-01-31 01:36 UTC, dsrev commented on Web/Presenters/templates/components/error.xml
> +</center>
... не совсем.

2022-01-31 07:04 UTC, maksalees approved these changes
dsrev пофиксил все, так что апрув

2022-01-31 07:39 UTC, veselcraft approved these changes
Да, всё оки

2022-01-31 13:46 UTC, veselcraft commented
@celestora, ждём вашего ревью

2022-02-01 10:36 UTC, celestora commented
> ждём вашего ревью

![image](https://user-images.githubusercontent.com/34442450/151953409-9f0d6274-5180-4d7d-b21e-fc6dc318cf6c.png)

2022-02-01 10:41 UTC, celestora requested changes

2022-02-01 10:41 UTC, celestora commented on Web/Presenters/templates/User/Groups.xml
> +            <a {if !$admin}id="act_tab_a"{/if} href="/groups{$user->getId()}">
n:attr

2022-02-01 10:41 UTC, celestora commented on Web/Presenters/templates/User/Groups.xml
> +            <input style="text-transform: lowercase; border-bottom: none; width: 140px;" type="submit" id="profile_link" value="{_"leave_community"}" />
`{_"leave_community"}` -> `{_leave_community}`

2022-02-01 10:44 UTC, dsrev commented on Web/Presenters/templates/User/Groups.xml
> +            <input style="text-transform: lowercase; border-bottom: none; width: 140px;" type="submit" id="profile_link" value="{_"leave_community"}" />
фига я слепой

2022-02-01 10:50 UTC, celestora commented on Web/Presenters/templates/User/Groups.xml
> +            <a {if !$admin}id="act_tab_a"{/if} href="/groups{$user->getId()}">
`n:attr='id: ($admin ? "" : "activetabs")'`
`n:attr='id: ($admin ? "" : "act_tab_a")'`

2022-02-01 11:19 UTC, celestora approved these changes

2022-02-01 11:20 UTC, merged