fixed the ability to delete comments from someone else's wall, from your post #446
OpenVK/openvk pull request #448
Opened 2022-02-01 19:11 UTC by vladimirlapskiy

2022-02-02 17:05 UTC, vladimirlapskiy commented
А вообще я забыл там добавить Users :D

2022-02-03 10:00 UTC, celestora requested changes
што?? зачем вы делаете abs над объектом и получаете по этому значению юзера?
смысл проверки, которую вы зачем-то убрали, был в том, чтобы убедиться, что владелец целевой сущности является тем же, кто хочет удалить.

2022-02-03 10:00 UTC, celestora commented on Web/Models/Entities/Comment.php
> +               (new Users)->get(abs($this->getTarget()))->getId() == $user->getId() ||
wtf???

2022-02-03 10:46 UTC, vladimirlapskiy commented
> зачем вы делаете abs над объектом и получаете по этому значению юзера?

Потому что выдаётся не числовое значение, но тут моя ошибка, я зачем-то её обернул в abs, даже не додумавшись использовать getId, удивительно что это вообще работало. 0_0

> смысл проверки, которую вы зачем-то убрали, был в том, чтобы убедиться, что владелец целевой сущности является тем же, кто хочет удалить.

но это тогда нарушает логику ВКонтакте, потому что владелец поста который запостил на чужой стене, не имеет права удалять комментарий, смотрите в issue [#446 ](https://github.com/openvk/openvk/issues/446)

2022-02-04 19:57 UTC, closed without merging