Similartovk
OpenVK/openvk pull request #450
Opened 2022-02-02 13:51 UTC by KosFurler

yes.

2022-02-05 14:39 UTC, celestora commented
![image](https://user-images.githubusercontent.com/34442450/152646320-31bc1b92-c742-424e-af61-b81816530ea8.png)

Теперь когда MCR, кто-нибудь может сказать шо делает этот PR конкретно, можно ли его уже проверять или неть?

2022-02-06 19:44 UTC, veselcraft requested changes
Кое-что нужно подшлейфовать, а так - прикольная штука

2022-02-06 19:44 UTC, veselcraft commented on Web/Presenters/templates/User/Groups.xml
> +    <div style="padding-bottom: 0px;border-bottom: 0;" class="summaryBar">
Так себе момент. Стоит это добавить в классы

2022-02-06 19:44 UTC, veselcraft commented on Web/Presenters/templates/User/Groups.xml
> +        <a style="border-bottom: none; width: 140px;" class="profile_link" href="{$x->getURL()}">
Хоть это и мой косяк, но тут тоже стоит добавить класс `.profile_link.short` из-за `width: 140px;`

2022-02-06 19:44 UTC, veselcraft commented on locales/ru.strings
> +"notes_list_other" = "Найдено $1 заметок";
[НЕ КРИТИЧНО] Мейби переменную лучше назвать `notes_found_*`?

2022-02-06 19:54 UTC, merged

2022-02-06 19:55 UTC, veselcraft commented
Костя, слишком рано мердж сделал

2022-02-06 19:56 UTC, WerySkok commented
ну можно нажать на revert

2022-02-07 10:08 UTC, celestora commented
> Костя, слишком рано мердж сделал

:trollface: