[WIP] Textarea: Add upload multiple pictures
OpenVK/openvk pull request #455
Opened 2022-02-04 13:46 UTC by veselcraft

Now there's thumbnail feature in TextArea box.

This is WIP, as the video is broken and posts doesn't feel good with multiple images

Resolves #311, resolves #427

2022-02-04 16:04 UTC, celestora requested changes
Это конечно драфт, но я всё равно испорчу удовольствие, ок?

2022-02-04 16:04 UTC, celestora commented on Web/Presenters/WallPresenter.php
> +	        $post->setNsfw($this->postParam("nsfw") === "on");
что с пробелами сестра

2022-02-04 16:04 UTC, celestora commented on Web/Presenters/WallPresenter.php
> +        	$post->attach($photo);
что с пробелами брат

2022-02-04 16:04 UTC, celestora commented on Web/static/css/style.css
> +}
рекоммендуется вверху

2022-02-04 16:04 UTC, celestora commented on Web/Presenters/WallPresenter.php
> +                if($file["error"] === UPLOAD_ERR_OK && preg_match('/^image\//', $file['type'])) {
В опенвк используется двойная кавычка
В опенвк используются % для регулярок
Регулярки будут медленные тут, хоть это и WA, лучше бы был strpos(...) === 0

2022-02-04 16:04 UTC, celestora commented on Web/static/js/al_wall.js
> +            alert('Низя.');
А как же `consloe.log("блять...")`?

2022-02-04 16:04 UTC, celestora commented on Web/static/js/al_wall.js
> +    u(`div#aP${idA}`).nodes[0].remove();
смешной айди непонятный

не рекоммендуется использовать такие ID. лучше использовать класс и вынести данные в data-* аттрибуты:
`<div class="aP" data-id="4">`

получить такие можно через селектор аттрибутов:
`.aP[data-id="4"]`

2022-02-04 16:04 UTC, celestora commented on Web/static/css/style.css
> +    margin-left: 57px; /* мне лень переделывать :DDDD */
![image](https://user-images.githubusercontent.com/34442450/152561705-e644581b-e045-4721-91d9-ed8b62ad7b73.png)

2022-02-04 16:05 UTC, celestora commented
> Это конечно драфт, но я всё равно испорчу удовольствие, ок?

p.s. мне кажется я верискок только в коде овк

2022-02-04 16:07 UTC, dsrev commented on Web/static/css/style.css
> +    margin-left: 57px; /* мне лень переделывать :DDDD */
OMG дополнительный 1 тб onedrive 😳

2022-02-04 16:07 UTC, WerySkok commented on Web/static/js/al_wall.js
> +            alert('Низя.');
Почему 4 кста. Я понимаю, что совместимость с другими сервисами федиверса и всё такое, но нам мало что мешает ебануть 10 как в вк.

2022-02-04 16:59 UTC, veselcraft commented on Web/static/css/style.css
> +}
что

2022-04-07 09:55 UTC, SigmaTel71 commented on Web/static/js/al_wall.js
> +            alert('Низя.');
> что мешает ебануть 10 как в вк.

Ебанём [сюда](https://media.discordapp.net/attachments/952656572054646864/961564627945283594/unknown.png?width)... [картинку](https://media.discordapp.net/attachments/952656572054646864/961564627639074826/unknown.png). (С)

2022-06-02 10:19 UTC, merged