Интеграция TON
OpenVK/openvk pull request #550
Opened 2022-05-07 15:45 UTC by veselcraft

Сделано это по следующим причинам:
1. Чтобы дурить налоговую
2. Всем привет с вами Дмитрий из Мариуполя и тут весь город в труху
3. визу и мк отключили в РСФСР
4. ротирнгпамчспшагкронларпомлронипммтиосьрпмтиосьрпиьстм

![image](https://user-images.githubusercontent.com/22993408/167261624-82c15372-caa1-4a94-984f-5d76bd755027.png)

*пожалуйста не кидайте на этот кошелек ничего он вообще в testnet находится а там тоны фейковые*

Думаю, это достойно включения в мастер ветку

2022-05-07 15:51 UTC, veselcraft commented
celestorius я жду ваших комментариев :trollface:

2022-05-07 15:51 UTC, veselcraft commented
каво я пулл не закрывал

2022-05-07 15:56 UTC, veselcraft commented
стоп а как сюда попали коммиты от textarea-refactor

2022-05-07 16:03 UTC, celestora requested changes
А что с файлом `WallPresenter` стало ору.
В остальном благодарна за то что вы прислушались к моим замечаниям, но есть определённые моменты, которые стоит исправить.

2022-05-07 16:03 UTC, celestora commented on CLI/FetchToncoinTransactions.php
> +        $counter->overwrite("Processing finished :3");
`$counter` -> `$header`

2022-05-07 16:03 UTC, celestora commented on CLI/FetchToncoinTransactions.php
> +                    $header->writeln(["Well, that's a donation. Thanks! XD"]);
Можно без `[]` же

2022-05-07 16:03 UTC, celestora commented on CLI/FetchToncoinTransactions.php
> +                $header->writeln(["Well, that's a donation. Thanks! XD"]);
Можно вроде без `[]`

2022-05-07 16:03 UTC, celestora commented on CLI/FetchToncoinTransactions.php
> +        $header->writeln(["Gonna up the balance of users"]);
Можно вроде без []

2022-05-07 16:03 UTC, celestora commented on CLI/FetchToncoinTransactions.php
> +        $response = json_decode($response, true);
Оформьте пж как рекурсивный метод для сбора более 100 транзакций спс

2022-05-07 16:05 UTC, veselcraft commented
> что с файлом WallPresenter стало 

чек тг

2022-05-07 16:05 UTC, veselcraft commented on CLI/FetchToncoinTransactions.php
> +        $response = json_decode($response, true);
потом мне лень уже

2022-05-07 16:06 UTC, veselcraft commented on CLI/FetchToncoinTransactions.php
> +        $response = json_decode($response, true);
Один хуй это все каждую минуту рекурсивно и потихоньку буде просираться

2022-05-09 12:01 UTC, veselcraft commented on CLI/FetchToncoinTransactions.php
> +        $response = json_decode($response, true);
Короче, фетчить более чем 100 транзакций получится только если лимиты увеличивать. А так нет, так что resolved

2022-05-13 18:55 UTC, maksalees requested changes
Вроде все хорошо, но:

- В некоторых местах нарушен стиль кода
- Некоторые изменения ломают форматирование в файлах которые на касаются этого PR

2022-05-13 18:55 UTC, maksalees commented on CLI/FetchToncoinTransactions.php
> +        $testnet_subdomain = OPENVK_ROOT_CONF["openvk"]["preferences"]["ton"]["testnet"] ? "testnet." : "";
Что насчет переименования всех этих переменных в cameCale, для соответсвия стилю кода?

2022-05-13 18:55 UTC, maksalees commented on Web/Presenters/WallPresenter.php
> -            $post = new Post;
????

2022-05-13 18:55 UTC, maksalees commented on Web/Presenters/templates/User/Settings.xml
> +                        ${ tr("transfer_ton_contents") }
```suggestion
                        ${tr("transfer_ton_contents")}
```

2022-05-13 18:55 UTC, maksalees commented on Web/Presenters/templates/User/Settings.xml
> +                u('.coins_dialog_conv').nodes[0].innerHTML = tr("transfer_ton_currency_per_ton", coin * currencyTON);
```suggestion
                u(".coins_dialog_conv").nodes[0].innerHTML = tr("transfer_ton_currency_per_ton", coin * currencyTON); 
```

2022-05-13 18:55 UTC, maksalees commented on Web/Presenters/templates/components/post/microblogpost.xml
> -            <td width="54" valign="top">
????

2022-05-13 18:55 UTC, maksalees commented on Web/static/css/style.css
> -    margin-top: 8px;
????

2022-05-13 18:55 UTC, maksalees commented on Web/static/js/al_wall.js
> -
????

2022-05-13 19:00 UTC, maksalees requested changes
И ещё чуть-чуть придирок

2022-05-13 19:00 UTC, maksalees commented on CLI/FetchToncoinTransactions.php
> +            if($userid === NULL) {
```suggestion
            if(is_null($userid)) {

```

2022-05-23 12:32 UTC, veselcraft commented on Web/Presenters/WallPresenter.php
> -            $post = new Post;
такой же вопрос кстати

2022-05-23 12:51 UTC, maksalees requested changes
![image](https://user-images.githubusercontent.com/50026114/169823221-8ebd328b-4459-4c1b-bcb1-63ccec15e336.png)

2022-05-23 12:51 UTC, maksalees commented on CLI/FetchToncoinTransactions.php
> +            $userid = ctype_digit($output_array[1]) ? intval($output_array[1]) : NULL;
Переименуй `$userid` на `$userId`

2022-05-23 12:51 UTC, maksalees commented on CLI/FetchToncoinTransactions.php
> +            $output_array;
Переименуй `$output_array` на `$outputArray`

2022-05-23 12:51 UTC, maksalees commented on Web/Presenters/WallPresenter.php
> -            $post = new Post;
![image](https://user-images.githubusercontent.com/50026114/169822277-0aef8a5a-194b-4ed1-a555-2faa07a5a0d8.png)
Ты немного не то исправил :3

2022-05-23 12:51 UTC, maksalees commented on Web/static/js/al_wall.js
> -
Чзх

2022-05-23 12:51 UTC, maksalees commented on CLI/FetchToncoinTransactions.php
> +            "to_lt" => $trLt
Не соответствует стилю кода :trollface:

2022-05-23 12:51 UTC, maksalees commented on CLI/FetchToncoinTransactions.php
> +        $trLt     = $selection->lt ?? NULL;
Не соответствует стилю кода :trollface:

2022-05-23 12:51 UTC, maksalees commented on CLI/FetchToncoinTransactions.php
> +        $url               = "https://" . $testnetSubdomain . "toncenter.com/api/v2/getTransactions?";
Не соответствует стилю кода :trollface:

2022-05-23 13:41 UTC, maksalees approved these changes
Теперь все хорошо, разве что я сейчас сам уберу лишние изменения отступов чтобы тебя не задалбывать

2022-06-02 10:19 UTC, merged