[WIP] Profile deletion function
OpenVK/openvk pull request #626
Opened 2022-08-03 06:32 UTC by dsrev

#141 #562

2022-08-03 14:05 UTC, dsrev commented
Есть ли смысл делать merge в таком состоянии? У нас есть полно времени, чтобы реализовать один из вариков удаления данных пользователя

2022-08-03 14:06 UTC, veselcraft commented
ИМХО, смысл имеет. Один хуй мы в ТП просто птичку "удалено" ставим

2022-08-03 14:13 UTC, veselcraft reviewed
одна есть некритическая помилка

2022-08-03 14:13 UTC, veselcraft commented on Web/static/js/openvk.cls.js
> +    document.querySelector("#deactivate_1").onclick = function () {
вот тут говнокодик, да. Предлагаю сделать event click по маске #deactivate_* и хранить в элементе текст с приколом

2022-08-03 17:08 UTC, veselcraft approved these changes
👍

2022-08-03 17:43 UTC, celestora requested changes
Много замечаний у мя про кодстайл и всякие мелкие приколы, из глобального - название некоторых колонок и методов очень стрёмные (deact_until... так это время удаления или время до которого акк деактивирован?). На самом деле если так подумать, то логика есть, акк деактивирован до удаления, но подобный ход мыслей очевиден не всем, мб добавить коммент в БД по поводу этой колонки? Хотя хз мб я ебебе, болею(
По этой же причине особо сильно проверить не удалось, но вроде всё нормально?

2022-08-03 17:43 UTC, celestora commented on Web/Models/Entities/Post.php
> +    }
Название откровенно неудачное, хотя смысл отражает, я бы назвал это `isDeactivationMessage` или как-то так

2022-08-03 17:43 UTC, celestora commented on Web/Models/Entities/User.php
> +        $name = $this->getRecord()->deleted && $this->getRecord()->deact_until <= time() ? "DELETED" : mb_convert_case($this->getRecord()->first_name, MB_CASE_TITLE);
В скобки нужно брать такое

2022-08-03 17:43 UTC, celestora commented on Web/Models/Entities/User.php
> +        $name = $this->getRecord()->deleted && $this->getRecord()->deact_until <= time() ? "DELETED" : mb_convert_case($this->getRecord()->last_name, MB_CASE_TITLE);
same as above

2022-08-03 17:43 UTC, celestora commented on Web/Models/Entities/User.php
> +        return $this->getRecord()->deleted && $this->getRecord()->deact_until <= time() ? "DELETED" : $this->getRecord()->pseudo;
my fucking god

2022-08-03 17:43 UTC, celestora commented on Web/Models/Entities/User.php
> +    function getDeactivatedUntil(): DateTime
Деактивирован до?)

2022-08-03 17:43 UTC, celestora commented on Web/Presenters/AuthPresenter.php
> +        exit;
Можно заменить `$this->redirect("/", 2);`?

2022-08-03 17:43 UTC, celestora commented on Web/Presenters/OpenVKPresenter.php
> -                */
куда?

2022-08-03 17:43 UTC, celestora commented on Web/Presenters/OpenVKPresenter.php
> +                        "isTimezoned" => Session::i()->get("_timezoneOffset"),
пробелы где

2022-08-03 17:43 UTC, celestora commented on Web/Presenters/OpenVKPresenter.php
> +                    $this->redirect("/", static::REDIRECT_TEMPORARY);
о а тут норм редир!

2022-08-03 17:43 UTC, celestora commented on Web/Presenters/SupportPresenter.php
> +    protected $deactivationTolerant = true;
редиска

2022-08-03 17:43 UTC, celestora commented on Web/Presenters/UserPresenter.php
>  use openvk\Web\Models\Repositories\Albums;
не по теме PR но можно было бы объеденить

2022-08-03 17:43 UTC, celestora commented on Web/Presenters/UserPresenter.php
> +        exit;
а тут редир неправильный

2022-08-03 17:43 UTC, celestora commented on Web/Presenters/templates/@layout.xml
> +                        </div>
в блоках {if} у нас вроде бы ещё отступы должны быть

2022-08-03 17:43 UTC, celestora commented on Web/static/js/openvk.cls.js
> +            document.querySelector("#profile_deactivate_dialog").submit();
а `$(...)` для кого

2022-08-03 17:43 UTC, celestora commented on Web/static/js/openvk.cls.js
> +        document.getElementById('deactivate_reason').value = $(this).data("text");
Same as above

2022-08-03 17:43 UTC, celestora commented on install/sqls/00028-deactivation.sql
> +ALTER TABLE `profiles` ADD `deact_until` bigint(20) unsigned NOT NULL DEFAULT '0' AFTER `deleted`, ADD `deact_reason` text NULL AFTER `deact_until`;
Название какое-то алогичное имхо

2022-08-03 17:47 UTC, celestora commented
Алсо в догонку: везде в условиях проверка со временем. Мб вынести в отдельный метод `User::isDeactivated`?

2022-08-03 17:49 UTC, celestora commented
<details>
<summary>спойлер к breaking bad</summary>

![image](https://user-images.githubusercontent.com/34442450/182675228-247f7c24-7f6b-4239-abad-c35ea0eeee2a.png)
</details>
<!-- mdextras 1.1.5a -->

2022-08-04 04:04 UTC, dsrev commented on Web/Presenters/OpenVKPresenter.php
> -                */
да

2022-08-04 04:26 UTC, dsrev commented on Web/Presenters/UserPresenter.php
>  use openvk\Web\Models\Repositories\Albums;
мб сделаю это вне pr

2022-08-04 09:13 UTC, celestora approved these changes
lgtm

2022-08-04 09:14 UTC, celestora commented
![image](https://user-images.githubusercontent.com/34442450/182810642-b590b3a7-a157-4c70-a5f4-04840f3667ad.png)

2022-08-05 20:00 UTC, celestora commented
максалес так и не посморел

2022-08-05 20:00 UTC, merged

2022-08-05 20:13 UTC, maksalees reviewed
Я забыл

2022-08-05 20:13 UTC, maksalees commented on Web/Models/Entities/User.php
> +        if ($this->getDeactivationDate()->timestamp() > time())
Не соответствует стилю кода

2022-08-05 20:13 UTC, maksalees commented on Web/Presenters/AuthPresenter.php
> +        exit;
`redirect` уже содержит в своем коде `exit`, так что тут его можно удалить

2022-08-05 20:13 UTC, maksalees commented on Web/Presenters/UserPresenter.php
>          exit;
`redirect` уже содержит в своем коде `exit`, так что тут его можно удалить

2022-08-05 20:13 UTC, maksalees commented on Web/Presenters/UserPresenter.php
> +        exit;
`redirect` уже содержит в своем коде `exit`, так что тут его можно удалить

2022-08-05 20:13 UTC, maksalees commented on Web/Presenters/templates/@deactivated.xml
> +            <center style="color: #AAA;margin: 40px 0;font-size: 13px;">
Может лучше добавить пробел между стилями?

2022-08-05 22:00 UTC, maksalees commented
Кстати, по идеи причина удаления страницы должна показываться на странице если выбрана галочка "Рассказать друзьям". Но этого не происходит

2022-08-06 03:31 UTC, dsrev commented
"Рассказать друзьям" просто отправляет пост с причиной деактивации на стену пользователя. Так, например, пост могут увидеть его друзья.

Поведение нынешнего ВК, не знаю как там было в старом

2022-08-06 14:39 UTC, GeorgNation commented
Считаю что оптимальным методом удаления данных будет следующее: Администратор инстанса может указать в конфигурации сколько времени аккаунт будет храниться как DELETED, прежде чем его удалить (на случай когда надо соблюдать законы о персональных данных), либо вообще просто анонимизировать аккаунт и закрыть доступ для простых людей, в том числе с возможностью удерживать аккаунты от их уничтожения. Также для user-friendly еще можно внедрить сохранение копии аккаунта в зашифрованном архиве со сжатием (через который в случае чего пользователь сам может вернуть все как есть при необходимости), который будет подписан ключом инстанса через крипто-алгоритмы для обеспечения сохранности (его можно будет восстановить один раз, потом в случае чего будет создан новый). Правда на случай если потом чужие люди будут занимать юзерки то также оповестить что здесь раньше находился удаленный аккаунт и если владелец его восстановит то она автоматически перейдет владельцу (в случае чего также администраторы могут полностью освободить юзерки на случаи если догадливые умы захотят украсть их делая и удаляя аккаунты заранее).