Архив записей
OpenVK/openvk pull request #660
Opened 2022-08-18 21:09 UTC by n1rwana

Архивация записей на стене пользователей и сообществ.

#202 
![image](https://user-images.githubusercontent.com/93197434/185495240-09c9d2aa-5bb0-47b0-ad26-eb01ffb0c961.png)
![image](https://user-images.githubusercontent.com/93197434/185495395-3e1d8e5d-01ad-4930-9a57-defd2f002f60.png)

2022-08-18 21:13 UTC, veselcraft commented
https://user-images.githubusercontent.com/22993408/185496068-90abafe0-e1a2-4035-8f73-032f163605b7.mp4

2022-08-18 21:15 UTC, myslivets commented
низуя себе, ну ты мощь прям

2022-08-18 21:24 UTC, el-psy-congroo-desu commented
https://user-images.githubusercontent.com/94683384/185497798-119ab341-713f-4465-aab5-1b8c43af85aa.mp4

2022-08-18 21:27 UTC, veselcraft commented
скинь свой телеграм срочно

2022-08-18 21:32 UTC, n1rwana commented
@n10628

2022-08-19 09:27 UTC, dsrev commented
Я конеш понимаю, что чел харош, но Вы сам PR проверили?

2022-08-19 09:48 UTC, dsrev commented on Web/Models/Entities/Post.php
> +        return (bool) $this->getRecord()->archive;
Думаю, лучше было бы сделать `archived`, чтобы сочеталось с остальными (кроме `anonymous`)

2022-08-19 09:50 UTC, dsrev commented on Web/Presenters/templates/Wall/Wall.xml
> +    {if $archive}{_"wall_archive"}{else}{_"wall"}{/if}
На будущее - достаточно написать просто `{_wall_archive}`

2022-08-19 09:50 UTC, dsrev commented on Web/Presenters/templates/components/post/oldpost.xml
> +                        {/if}
Это явно лишнее

2022-08-19 09:51 UTC, dsrev commented on install/sqls/00030-wall-archive.sql
> +ALTER TABLE `posts` ADD `archive` TINYINT NOT NULL DEFAULT '0' AFTER `archive`;
Мы не можем добавить `archive` после `archive`.

2022-08-19 09:51 UTC, dsrev requested changes
Approve, но есть небольшие недочёты

2022-08-19 09:58 UTC, dsrev approved these changes

2022-08-19 09:58 UTC, merged

2022-10-16 14:46 UTC, veselcraft commented
Мердж Шрёдингера. Куда функционал спиздили? Я чот не вижу архивации нигде

2022-10-16 14:47 UTC, veselcraft commented
Именно в основной ветке

2022-10-16 14:54 UTC, AlesAlte commented
> Мердж Шрёдингера. Куда функционал спиздили? Я чот не вижу архивации нигде

Вы его вроде-как убрали, потому что он кривой. В телеграм беседе перешлю видео.