"Показать больше" в постах
OpenVK/openvk pull request #668
Opened 2022-08-19 10:54 UTC by n1rwana

#570

2022-08-19 11:19 UTC, veselcraft requested changes
кстати а можно скриншотики

2022-08-19 11:19 UTC, veselcraft commented on locales/ru.strings
> +"wall_show_more" = "Показать больше...";
в ориг вк была надпись "Показать полностью..."

2022-08-19 11:33 UTC, celestora requested changes

2022-08-19 11:33 UTC, celestora commented on Web/Presenters/templates/components/post/oldpost.xml
> +                            {mb_substr($post->getText(), 0, 35)|noescape}
вы не представляете что произойдёт если там будет тег :DD

2022-08-19 11:33 UTC, celestora commented on Web/Presenters/templates/components/post/oldpost.xml
> +                                onClick="this.style.display = 'none'; document.getElementById('hidden-content-{$post->getVirtualId()}').style.display = 'inline';"
я не думаю что вообще так делать приемлемо. думаю лучше будет вынести это в отдельный обработчик в какой-нибудь js файл и не засирать пространство имён переменными XXX-YY (content-3424)

2022-08-19 11:41 UTC, celestora commented
Алсо не слишком ли мало 35 символов? Даже если опустить теги из внимания и учесть что тут речь идёт именно о знаках а не байтах, это как-то... маловато?
По поводу корректной обрезки: думаю стоит утащить вот этот метод из CakePHP куда-то в openvk (bootstrap.php require?):
https://github.com/cakephp/utility/blob/4259ae4154e639557af751ae719d58253a79282a/Text.php#L600

С настройками exact: false, html: true должно получится вполне себе годно, без XSS приколов. Вообще давно пора это утащить а то из-за того что у нас такого нет в уведомлениях текст не хтмльный(

2022-08-19 12:22 UTC, n1rwana commented
![image](https://user-images.githubusercontent.com/93197434/185617263-079d391d-1116-4c24-a47a-a5a608d6a3ea.png)

2022-08-20 20:56 UTC, celestora commented on Web/static/js/jquery.collapser.js
> +/*
Решение элегантное, вопрос только в том оправдано ли встраивание библиотеки в овк? Её нельзя добавить через yarn?

2022-08-20 21:02 UTC, n1rwana commented on Web/static/js/jquery.collapser.js
> +/*
К сожалению, на официальном сайте её можно только скачать

https://www.aakashweb.com/jquery-plugins/collapser/

2022-08-21 16:34 UTC, celestora commented on Web/static/js/jquery.collapser.js
> +/*
Судя по репе вполне себе можно через `cd Web/static/js && yarn add jquery-collapser`

2022-08-21 19:43 UTC, n1rwana commented on Web/static/js/jquery.collapser.js
> +/*
![image](https://user-images.githubusercontent.com/93197434/185808214-45faa3ad-80e6-48b2-9dfd-72ead6d08f88.png)

2022-08-28 11:46 UTC, celestora commented on Web/static/js/jquery.collapser.js
> +/*
ok

2022-08-28 11:47 UTC, merged