Shortcode aliases
OpenVK/openvk pull request #690
Opened 2022-08-25 22:27 UTC by n1rwana

Добавляет алиасы для коротких адресов.

Пример из VK:
https://vk.com/team
https://vk.com/vk

2022-08-25 22:28 UTC, celestora commented
Интересно зачем

2022-08-28 11:03 UTC, veselcraft commented
> Интересно зачем

сколько раз ты набирал 7zip.org вместо 7-zip.org? :trollface:

2022-08-28 11:44 UTC, celestora requested changes

2022-08-28 11:44 UTC, celestora commented on Web/Models/Repositories/Clubs.php
> +        else {
скобки должны быть либо во всех случаях либо ни в каких, комбинировать кринж, но тут ещё return, не понятно зачем else вообще нужен

2022-08-28 11:44 UTC, celestora commented on Web/Models/Repositories/Users.php
> +        else {
сейм

2022-08-28 11:44 UTC, celestora commented on install/sqls/00032-shortcode-aliases.sql
> +    `id` bigint NOT NULL,
поч не unsigned?

2022-08-28 16:15 UTC, n1rwana commented on install/sqls/00032-shortcode-aliases.sql
> +    `id` bigint NOT NULL,
Адрес может принадлежать сообществу, поэтому `id` может быть меньше 0

![image](https://user-images.githubusercontent.com/93197434/187083873-ef2e64d0-f328-4a70-a1c7-ea76623aa0fe.png)

2022-09-03 20:21 UTC, veselcraft approved these changes
вприцнипе всё ок но про новые строки в конце файла не забывай

2022-09-03 20:21 UTC, veselcraft commented on Web/Models/Entities/Alias.php
> +}
брат newline

2022-09-03 20:21 UTC, veselcraft commented on Web/Models/Repositories/Aliases.php
> +}
https://en.wikipedia.org/wiki/Newline

2022-09-03 20:21 UTC, veselcraft commented on install/sqls/00032-shortcode-aliases.sql
> +COMMIT;
https://uk.wikipedia.org/wiki/%D0%A1%D0%B8%D0%BC%D0%B2%D0%BE%D0%BB_%D0%BD%D0%BE%D0%B2%D0%BE%D0%B3%D0%BE_%D1%80%D1%8F%D0%B4%D0%BA%D0%B0

2022-09-04 07:36 UTC, veselcraft approved these changes
https://user-images.githubusercontent.com/22993408/188302771-d0eaf19d-a9f5-445f-9c38-890efb216a07.mp4

2022-09-16 21:08 UTC, veselcraft commented
Функция готова? Можно мерджить?

2022-09-16 21:20 UTC, n1rwana commented
Теперь да.

2022-09-16 21:21 UTC, merged