Возможность блокировки домена
OpenVK/openvk pull request #693
Opened 2022-08-26 19:39 UTC by n1rwana

Добавляет возможность заблокировать ссылки на определённый домен на инстансе. Если домен заблокирован, переход на него не будет совершён, а пользователь увидит ошибку с описанием причины блокировки.
![image](https://user-images.githubusercontent.com/93197434/186978615-0362ab48-35de-4eec-a386-bc77443104ba.png)
![image](https://user-images.githubusercontent.com/93197434/186979127-964063f7-ba9a-4df9-a21d-a77a7b43d5d1.png)
![image](https://user-images.githubusercontent.com/93197434/186979153-efa5022a-dafc-4e2c-9957-2c31e7c6e6c3.png)

2022-08-26 19:40 UTC, themohooks commented
чел ты ахуенен, поделись пожалуйста мозгами, я тоже хочу выучить чандлер блин

2022-08-26 19:41 UTC, AlesAlte commented
А если ссылка подозрительная (но переход возможен)?

P.S Ссылки лучше открывать в новой вкладке.

2022-08-26 19:42 UTC, saursvepur commented
Эх, мне бы такого кодера в инстанс..

2022-08-26 19:51 UTC, veselcraft commented
А почему бы это не сделать в виде отдельной страницы away.php, как это сделано в оригинале?

2022-08-26 19:53 UTC, celestora requested changes
Стоит завести модельки и репки, чтобы избавиться от некоторых спагетти-моментов и толстых контроллеров.

2022-08-26 19:53 UTC, celestora commented on Web/Models/Entities/Traits/TRichText.php
> +                return "<a href='/away.php?to=$href' rel='$rel' target='_blank'>$link</a>" . htmlentities($matches[4]);
`$href` стоит тогда дополнительно пропустить через `rawurlencode` чтобы ссылки не портились.

2022-08-26 19:53 UTC, celestora commented on Web/Presenters/AdminPresenter.php
> +            $link = DatabaseConnection::i()->getContext()->table("links_banned")->where("id", $id)->fetch();
`->where("id", $x)->fetch()` замечательно можно заменить на `->get($x)`

2022-08-26 19:53 UTC, celestora commented on Web/Presenters/AdminPresenter.php
> +        $link = DatabaseConnection::i()->getContext()->table("links_banned")->where("id", $id)->fetch();
same

2022-08-26 19:53 UTC, celestora commented on Web/Presenters/AdminPresenter.php
> +                ->query("UPDATE `links_banned` SET `link` = '$new_link', `reason` = '$new_reason' WHERE `links_banned`.`id` = $id");
чем не устроило `->where("id", $x)->update([...]);`? вообще по хорошему для этой вещи стоит завести отдельную модель `LinkRule` или что-то такое.

2022-08-26 19:53 UTC, celestora commented on Web/Presenters/AwayPresenter.php
> +            $this->flashFail("err", tr("url_is_banned"), tr("url_is_banned_comment", OPENVK_ROOT_CONF["openvk"]["appearance"]["name"], $banned_link->reason ?: tr("url_is_banned_default_reason")));
мне кажется стоит отдельный шаблон завести чтобы как в вк

2022-08-26 19:54 UTC, celestora commented
> А почему бы это не сделать в виде отдельной страницы away.php, как это сделано в оригинале?

там всё идёт через away.php, просто он не шаблон добавил, а flashFail, думаю исправить это не так уж сложно

2022-08-26 19:56 UTC, myslivets commented
чел, мощь

2022-08-26 19:59 UTC, volodymyr6 commented
не мощь

2022-08-26 19:59 UTC, volodymyr6 commented
@volodymyr6 Харош

2022-08-26 21:10 UTC, n1rwana commented
1. Добавлен шаблон для `/away.php`
2. Добавлены модели и репозитории
3. Теперь в конфиге `openvk.yml` можно указать, нужно ли блокировать переход по заблокированным ссылкам и нужно ли показывать причину блокировки пользователю.
![image](https://user-images.githubusercontent.com/93197434/186990575-725d2aa2-99e2-4410-a50a-07e66de46f3c.png)

2022-08-26 21:11 UTC, veselcraft commented
кстати, а там бан по маске есть?

2022-08-26 21:14 UTC, maksalees commented
> 1. Добавлен шаблон для `/away.php`
> 
>     2. Добавлены модели и репозитории
> 
>     3. Теперь в конфиге `openvk.yml` можно указать, нужно ли блокировать переход по заблокированным ссылкам и нужно ли показывать причину блокировки пользователю.
>        ![image](https://user-images.githubusercontent.com/93197434/186990575-725d2aa2-99e2-4410-a50a-07e66de46f3c.png)

Может лучше убрать картинку из ВК и заменить ее на
![)))))))](https://openvk.su/assets/packages/static/openvk/img/oof.apng)

2022-08-26 21:14 UTC, n1rwana commented
> кстати, а там бан по маске есть?

Сейчас `AwayPresenter` проверяет только домен из ссылки. В реальном ВК вроде так же

![image](https://user-images.githubusercontent.com/93197434/186991300-8ffefcb9-323f-486a-9af3-9ab9324e4c32.png)
![image](https://user-images.githubusercontent.com/93197434/186991505-3fbaf4fc-d7f1-446c-b856-d20cbf80a617.png)

2022-08-26 21:16 UTC, AlesAlte commented
> реальном ВК вроде так же

Ну и что, что в оригинальном ВК так же? Вы можете сделать лучше, чем у них.

2022-08-26 21:18 UTC, maksalees commented
> > кстати, а там бан по маске есть?
> 
> Сейчас `AwayPresenter` проверяет только домен из ссылки. В реальном ВК вроде так же
> 
> ![image](https://user-images.githubusercontent.com/93197434/186991300-8ffefcb9-323f-486a-9af3-9ab9324e4c32.png) ![image](https://user-images.githubusercontent.com/93197434/186991505-3fbaf4fc-d7f1-446c-b856-d20cbf80a617.png)

Но плохим может быть не весь домен, а только одна опубликованная пользователем страница

2022-08-26 21:19 UTC, n1rwana commented
> Может лучше убрать картинку из ВК и заменить ее на

Готово. :)

![image](https://user-images.githubusercontent.com/93197434/186992029-4e75a74c-0bf6-4564-b94f-716702913b8a.png)

2022-08-26 21:22 UTC, maksalees commented
> Теперь в конфиге `openvk.yml` можно указать, нужно ли блокировать переход по заблокированным ссылкам и нужно ли показывать причину блокировки пользователю.

Я думаю что блокировать переход является не очень хорошей идеей, так как это ограничивает свободу пользователя. Также он может просто скопировать ссылку и сам по ней перейти. Может лучше просто предупреждать, а функционал блокировки вообще выпилить?

2022-08-26 23:17 UTC, n1rwana commented
1. Теперь при блокировке применяются регулярные выражения, т.е. можно забанить не весь домен сразу, а только некоторые страницы на нём.
2. Добавлена кнопка `Перейти по ссылке` в шаблон `/away.php`

![image](https://user-images.githubusercontent.com/93197434/187001740-d525f68e-5977-40a7-9b7b-d2a9572dfab4.png)
![image](https://user-images.githubusercontent.com/93197434/187001903-3bfae429-0bcc-405e-86d6-35b388e58b0e.png)

2022-08-27 07:13 UTC, cheburashka777 commented
> > 1. Добавлен шаблон для `/away.php`
> > 
> >     2. Добавлены модели и репозитории
> > 
> >     3. Теперь в конфиге `openvk.yml` можно указать, нужно ли блокировать переход по заблокированным ссылкам и нужно ли показывать причину блокировки пользователю.
> >        ![image](https://user-images.githubusercontent.com/93197434/186990575-725d2aa2-99e2-4410-a50a-07e66de46f3c.png)
> 
> Может лучше убрать картинку из ВК и заменить ее на
> ![)))))))](https://openvk.su/assets/packages/static/openvk/img/oof.apng)
> ?
> 

А может лучше на ту, где серый лого опенвк с каплей или с восклицательным знаком? По тематике больше подходит.

2022-08-28 11:10 UTC, veselcraft requested changes
По коду всё окей, но ещё не хватает локализации и кое-где профукана новая строка в конце файла

2022-08-28 11:10 UTC, veselcraft commented on Web/Models/Entities/BannedLink.php
> +}
newline забыл

2022-08-28 11:10 UTC, veselcraft commented on Web/Presenters/AdminPresenter.php
> +                $this->flashFail("err", "Ошибка", "Ссылка не указана");
localize this string

2022-08-28 11:10 UTC, veselcraft commented on Web/Presenters/AdminPresenter.php
> +            $this->flashFail("err", "Ошибка", "Ссылка не найдена");
здесь тоже

2022-08-28 11:10 UTC, veselcraft commented on Web/Presenters/BannedLinkPresenter.php
> +}
newline

2022-08-28 11:10 UTC, veselcraft commented on Web/Presenters/templates/Admin/BannedLink.xml
> +{/block}
newline

2022-08-28 11:10 UTC, veselcraft commented on Web/Presenters/templates/Admin/BannedLink.xml
> +            </div>
кек это всё добро только на половину локализировано)

2022-08-28 11:10 UTC, veselcraft commented on Web/Presenters/templates/Admin/BannedLinks.xml
> +                <th>REGEXP</th>
ну ты понел

2022-08-28 11:10 UTC, veselcraft commented on Web/Presenters/templates/BannedLink/View.xml
> +{/block}
ну и тут тоже + newline

2022-08-28 11:37 UTC, celestora requested changes

2022-08-28 11:37 UTC, celestora commented on Web/Models/Entities/Traits/TRichText.php
> +                return "<a href='/away.php?to=$href' rel='$rel' target='_blank'>$link</a>" . htmlentities($matches[4]);
а где rawurlencode

2022-08-28 11:37 UTC, celestora commented on Web/Models/Entities/BannedLink.php
> +        return '/' . $this->getDomain() . $this->getRecord()->regexp_rule . '/';
здесь отсутствуют addslashes. хз, мб они где-то тут не нужны, но мб будет прикольчик уровня /gustavo.org/ который по сути будет позитивным для всех подоюных случаев:
http://gustavo.org/
http://gustavomorg.ru/
http://twitter.com/gustavo_org

либо я чего-то не понимаю либо это поведение лучше переделать ибо ржака

2022-08-28 11:37 UTC, celestora commented on Web/Models/Repositories/BannedLinks.php
> +        return !is_null(DB::i()->getConnection()->query("SELECT * FROM `links_banned` WHERE `link` = '$domain' AND `regexp_rule` = ''")->fetch());
не понятно почему не используется `sizeof($this->bannedLinks->where(["link" => $domain, "regexp_rule" => ""])) > 0`

2022-08-28 11:37 UTC, celestora commented on Web/Presenters/BannedLinkPresenter.php
> +    function renderView(int $lid) {
newline

2022-08-28 11:37 UTC, celestora commented on Web/Presenters/AdminPresenter.php
> +        $this->template->links = DatabaseConnection::i()->getContext()->table("links_banned");
зачем нам бог подарил модели если можно так :DDD

здесь не предусмотрена пагинация и это не итератор моделей из репозитория, надо бы переделоть, а то как-то не оч

2022-08-28 11:37 UTC, celestora commented on Web/Presenters/AwayPresenter.php
> +
лишний перевод строки

2022-08-28 11:37 UTC, celestora commented on Web/Presenters/AwayPresenter.php
> +        }
лишние скобки

2022-08-28 11:37 UTC, celestora commented on Web/Presenters/AdminPresenter.php
> +        $link->delete(FALSE);
поч с большой буквы

2022-08-28 11:37 UTC, celestora commented on Web/Presenters/AdminPresenter.php
> +
зач

2022-08-28 11:37 UTC, celestora commented on Web/Models/Repositories/BannedLinks.php
> +        $uri = preg_replace("(^https?://)", "", $url);
Зачем здесь регулярка, долго же

2022-08-28 11:37 UTC, celestora commented on Web/Models/Repositories/BannedLinks.php
> +        $domain = preg_replace('/^www\./', '', parse_url($url)["host"]);
parse_url вполне себе может вернуть NULL, что приведёт к

2022-08-28 11:37 UTC, celestora commented on Web/Models/Repositories/BannedLinks.php
> +        $rulesForDomain = $this->getByDomain($domain);
TypeError здесь

2022-08-28 11:37 UTC, celestora commented on Web/Models/Repositories/BannedLinks.php
> +
много лишних переводов строки

2022-08-28 11:37 UTC, celestora commented on Web/Models/Repositories/BannedLinks.php
> +        {
по кодстайлу у циклов скобка стоит на той же строке

2022-08-28 11:37 UTC, celestora commented on Web/Models/Repositories/BannedLinks.php
> +        {
а здесь они вовсе лишние

2022-08-28 11:37 UTC, celestora commented on Web/Models/Repositories/BannedLinks.php
> +        return $entries;
не понятно почему бы не сделать и то и другое действие в одном цикле и использовать `yield` вместо накопления массивов

2022-08-28 11:37 UTC, celestora commented on Web/routes.yml
> +    - url: "/away.php&banned=1&lid={num}"
в роутах мы не прописываем query string, мы получаем эти данные динамически в презентере через `queryParam`

2022-08-28 11:37 UTC, celestora commented on install/sqls/00031-banned-urls.sql
> +    `id` bigint NOT NULL,
поч не unsigned?

2022-08-28 11:37 UTC, celestora commented on install/sqls/00031-banned-urls.sql
> +    `domain` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
поч не varchar?

2022-08-28 11:37 UTC, celestora commented on install/sqls/00031-banned-urls.sql
> +    `regexp_rule` text NOT NULL,
поч не varchar?

2022-08-28 11:37 UTC, celestora commented on install/sqls/00031-banned-urls.sql
> +    `reason` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
ну ладно тут ещё можно text юзать

2022-08-28 11:37 UTC, celestora commented on install/sqls/00031-banned-urls.sql
> +    `initiator` bigint NOT NULL
поч не unsigned?

2022-08-28 13:22 UTC, n1rwana commented on Web/Models/Entities/BannedLink.php
> +        return '/' . $this->getDomain() . $this->getRecord()->regexp_rule . '/';
Не будет, с правилом `/gustavo.org/` заблокируется только http://gustavo.org

![image](https://user-images.githubusercontent.com/93197434/187076018-b870a951-4198-4816-877c-2adb4d22f699.png)

2022-08-28 20:55 UTC, veselcraft commented
хаха тебя вообще не жалеют

![image](https://user-images.githubusercontent.com/22993408/187094154-87cf6b1b-1c12-46c0-839c-3b51a504999c.png)

2022-08-28 20:59 UTC, veselcraft approved these changes
параметр смешной в openvk.yml а так

https://user-images.githubusercontent.com/22993408/187094287-5d0189b9-5e3c-4a91-a85b-781fdb7a73d8.mp4

2022-08-28 20:59 UTC, veselcraft commented on openvk-example.yml
> +        susLinks:
https://user-images.githubusercontent.com/22993408/187094241-d19382a2-2d61-427e-858e-5508dfb72711.mp4

2022-09-05 15:57 UTC, merged