Чёрный список
OpenVK/openvk pull request #695
Opened 2022-08-27 15:45 UTC by n1rwana

Добавляет возможность вносить пользователей в чёрный список. При добавлении пользователя `target` в чёрный список пользователя `author`, от пользователя `target` полностью скрывается страница пользователя `author`, и весь его контент, такой как фотографии, видео, заметки, список друзей и групп.

Если добавить в ЧС администратора инстанса, на него не будут действовать ограничения, и он по-прежнему будет видеть страницу и контент пользователя.

![image](https://user-images.githubusercontent.com/93197434/187037499-36d6e706-ff99-4aa4-8abe-041c33f3ce01.png)
![image](https://user-images.githubusercontent.com/93197434/187037485-d4c71936-482e-4831-9ed8-ee95cf0a3079.png)

Resolve #226

2022-08-27 17:23 UTC, celestora commented
@n1rwana Плохая идея

2022-08-27 17:24 UTC, celestora commented
@n1rwana А нет реализация неплохая, но есть пара замечаний, завтра посмотрю

2022-08-27 19:54 UTC, AlesAlte commented
> Если добавить в ЧС администратора инстанса, на него не будут действовать ограничения, и он по-прежнему будет видеть страницу и контент пользователя.

Зачем?

2022-08-27 20:23 UTC, n1rwana commented
> Зачем?

Например, если на пользователя отправят жалобу _в тех. поддержку_, а Агент Поддержки каким-то образом окажется в ЧС. `¯\_(ツ)_/¯`

Добавил возможность настроить это в конфиге.

2022-08-28 01:49 UTC, AlesAlte commented
> Агент Поддержки каким-то образом окажется в ЧС

Если на то пошло, то можно главным администраторам показывать всю информацию, а второстепенным только субъект жалобы, но для этого нужно расширить функционал репортов.

2022-08-28 11:00 UTC, veselcraft commented
Чуть не забыл, а что насчёт API? Если человек в черном списке, то он как-нибудь тоже должен ограничиваться

2022-08-28 11:41 UTC, celestora requested changes

2022-08-28 11:41 UTC, celestora commented on Web/Models/Repositories/Blacklists.php
> +        return sizeof(DB::i()->getContext()->table("blacklists")->where(["author" => $author->getId(), "target" => $target->getId()])->fetch()) > 0;
у вас эта таблица буквально в `$this->blacklists` :D

2022-08-28 11:41 UTC, celestora commented on Web/Presenters/BlacklistPresenter.php
> +        $record = new BlacklistItem(DB::i()->getContext()->table("blacklists")->where([ "author" => $this->user->identity->getId(), "target" => $this->postParam("id") ])->fetch());
Это действие (получение сущности по критериям) должно быть в репозитории

2022-08-28 11:41 UTC, celestora commented on Web/Presenters/BlacklistPresenter.php
> +        $record->delete(FALSE);
большие буквы опять зачем, у нас тока нулл с бальшой буквы

2022-08-28 11:41 UTC, celestora commented on Web/Presenters/VideosPresenter.php
> +                $this->flashFail("err", tr("forbidden"), "Пользователь внёс Вас в чёрный список.");
вот этот кусок кода повторяется 100500 раз, не будет ли логичнее его запихнуть в `User::getPrivacyPermission` и возвращать им false в самом начале?

2022-09-03 20:27 UTC, veselcraft requested changes
ну тут пару изменений 👉👈

2022-09-03 20:27 UTC, veselcraft commented on Web/Models/Entities/User.php
> +            return false;
достаточно `return $user->isAdmin()`

2022-09-03 20:27 UTC, veselcraft commented on Web/Presenters/BlacklistPresenter.php
> +    function renderAddToBl(): void
я бы написал здесь полное название метода

2022-09-03 20:27 UTC, veselcraft commented on Web/Presenters/NotesPresenter.php
> +                $this->flashFail("err", tr("forbidden"), "Пользователь внёс Вас в чёрный список.");
по хорошему я бы строку перевёл в файл с локализацией

2022-09-03 20:27 UTC, veselcraft commented on Web/Presenters/PhotosPresenter.php
> +                    $this->flashFail("err", tr("forbidden"), "Пользователь внёс Вас в чёрный список.");
тоже самое

2022-09-03 20:27 UTC, veselcraft commented on Web/Presenters/PhotosPresenter.php
> +                    $this->flashFail("err", tr("forbidden"), "Пользователь внёс Вас в чёрный список.");
тут

2022-09-03 20:27 UTC, veselcraft commented on Web/Presenters/PhotosPresenter.php
> +            $this->flashFail("err", tr("forbidden"), "Пользователь внёс Вас в чёрный список.");
и тут ещё

2022-09-03 20:27 UTC, veselcraft commented on Web/Presenters/UserPresenter.php
> +                $this->flashFail("err", tr("forbidden"), "Пользователь внёс Вас в чёрный список.");
и здесь

2022-09-03 20:27 UTC, veselcraft commented on VKAPI/Handlers/Users.php
> +						"can_access_closed" => !(new Blacklists)->isBanned($usr, $authuser),
я бы ещё в fields добавил значение `blacklisted` и `blacklisted_by_me`, см. https://dev.vk.com/method/users.get

2022-09-03 20:27 UTC, veselcraft commented on VKAPI/Handlers/Users.php
> +                    if (!(new Blacklists)->isBanned($usr, $authuser))
съехало)

2022-09-03 20:27 UTC, veselcraft commented on VKAPI/Handlers/Users.php
> +                    if (!(new Blacklists)->isBanned($usr, $authuser))
и тут съехало

2022-09-03 20:27 UTC, veselcraft commented on Web/Presenters/BlacklistPresenter.php
> +}
братааааааааааан newline

2022-09-03 20:27 UTC, veselcraft commented on Web/Presenters/NotesPresenter.php
> +use openvk\Web\Models\Repositories\{Users, Notes, Blacklists};
в заметки добавил, а заюзать забыл

2022-09-03 20:27 UTC, veselcraft commented on Web/Presenters/PhotosPresenter.php
> +                $this->flashFail("err", tr("forbidden"), "Пользователь внёс Вас в чёрный список.");
localize this

2022-09-03 20:27 UTC, veselcraft commented on Web/Presenters/PhotosPresenter.php
> +                $this->flashFail("err", tr("forbidden"), "Пользователь внёс Вас в чёрный список.");
localize this

2022-09-03 20:27 UTC, veselcraft commented on Web/Presenters/UserPresenter.php
> +                            $this->flashFail("err", tr("forbidden"), "Пользователь внёс Вас в чёрный список.");
localize this

2022-09-03 20:27 UTC, veselcraft commented on Web/Presenters/UserPresenter.php
> +                        $this->flashFail("err", tr("forbidden"), "Пользователь внёс Вас в чёрный список.");
localize this

2022-09-03 20:27 UTC, veselcraft commented on Web/Presenters/VideosPresenter.php
> +                $this->flashFail("err", tr("forbidden"), "Пользователь внёс Вас в чёрный список.");
localize this

2022-09-03 20:27 UTC, veselcraft commented on Web/Presenters/templates/User/Settings.xml
> +            <a n:attr="id => ($isBlackList ? 'act_tab_a' : 'ki')" href="/settings?act=blacklist">Чёрный список</a>
localize this

2022-09-03 20:27 UTC, veselcraft commented on Web/Presenters/templates/User/View.xml
> +                Пользователь внёс Вас в чёрный список
localize this

2022-09-03 20:27 UTC, veselcraft commented on Web/di.yml
> +    - openvk\Web\Models\Repositories\Blacklists
https://ru.wikipedia.org/wiki/%D0%9F%D0%B5%D1%80%D0%B5%D0%B2%D0%BE%D0%B4_%D1%81%D1%82%D1%80%D0%BE%D0%BA%D0%B8

2022-09-04 07:38 UTC, veselcraft approved these changes
Всё гуд, но есть две переведённые строки и nl

2022-09-04 07:38 UTC, veselcraft commented on VKAPI/Handlers/Users.php
> +                        "blacklisted_by_me" => (new Blacklists)->isBanned($authuser, $usr)
куда строка съехала

2022-09-04 07:38 UTC, veselcraft commented on Web/Presenters/BlacklistPresenter.php
> +        $this->flashFail("succ", "Успех", $target->getCanonicalName() . " занесён в чёрный список.");
ой а тут тоже забыл

2022-09-04 07:38 UTC, veselcraft commented on Web/Presenters/BlacklistPresenter.php
> +        $this->flashFail("succ", "Успех",  "$name удалён из чёрного списка.");
и тут тож

2022-09-04 07:38 UTC, veselcraft commented on locales/ru.strings
> +"user_blacklisted_you" = "Пользователь внёс Вас в чёрный список.";
\n

2022-09-04 07:38 UTC, veselcraft commented on locales/en.strings
> +"user_blacklisted_you" = "This user has blacklisted you.";
\n

2022-09-16 21:07 UTC, veselcraft commented
@celestora сестра проверь пулл пж 👉👈

2023-01-11 10:41 UTC, veselcraft commented
актуально?

2023-01-11 15:31 UTC, WerySkok commented
Ого я даже и не подозревал про существование сего замечательного пр

2023-01-28 08:20 UTC, dsrev commented
Актуально? @celestora проверь

2023-03-26 11:53 UTC, NoPlagiarism commented
@n1rwana время обнов

2023-06-15 09:21 UTC, veselcraft commented
@n1rwana можешь свою ветку в нашу организацию перебросить? я допилю скорее всего

2023-06-28 22:06 UTC, aqukie commented
Стоит ещё учесть, что с появлением поиска, нужно добавить скрытие постов\коментариев пользователя в поиске.

2023-10-03 18:19 UTC, damirap2020 commented
ну че когда

2023-10-03 18:32 UTC, WerySkok commented
Там мерж конфликт

2023-11-10 18:12 UTC, JBLHRD commented
Мержните (или допилите) PR, пожалуйста, меня этот индивид заеб
![image](https://github.com/openvk/openvk/assets/147275844/aa7ac5be-1fc4-455d-9bc2-42591d84b746)

2023-11-10 22:19 UTC, veselcraft commented
@JBLHRD этот хуебес нас тоже заебал кстати

2024-12-11 13:30 UTC, nbt1248 commented
НУ ЧЁ КОГДА
ПОЧИНИТЕ УЖЕ СВОИ КОНФЛИКТЫ

2024-12-11 18:01 UTC, mrilyew commented
ну ветку в этом репо я обновил а как её здесь обновить то

2024-12-11 18:31 UTC, mrilyew commented
Ладно, обновить эту ветку вряд ли удастся, но зацените короч
![1](https://github.com/user-attachments/assets/0e765f5a-cad7-4427-a906-0a6ab8f9492a)
![2](https://github.com/user-attachments/assets/8fce73c1-09c5-409f-b5e1-e31d9e6f49ef)

2024-12-13 15:22 UTC, closed without merging