Редактирование постов
OpenVK/openvk pull request #696
Opened 2022-08-28 11:09 UTC by n1rwana

Добавляет возможность редактировать посты.
![image](https://user-images.githubusercontent.com/93197434/187071062-4d1a0ddb-f354-46d3-b15f-bce4bd424e70.png)

2022-08-28 11:18 UTC, celestora commented
![image](https://user-images.githubusercontent.com/34442450/187071413-56258d10-d86a-4317-ae92-f104d540795f.png)

2022-08-28 11:20 UTC, celestora requested changes
меня напрягает отсутствие хранения истории изменений (в сжатом виде) и возможности админам просмотреть её

2022-08-28 18:22 UTC, n1rwana commented
Теперь изменения будут логироваться, если выставить соответствующее значение в конфиге инстанса

![image](https://user-images.githubusercontent.com/93197434/187088926-67fe080d-7bc1-4c61-acc8-b3b446400ed3.png)

2022-08-30 18:18 UTC, AlesAlte commented
А что с комментариями?

2022-09-03 20:33 UTC, veselcraft reviewed
https://user-images.githubusercontent.com/22993408/188286865-cfa8c8bd-1c51-4ed9-8a80-c97b631fbd9a.mp4

2022-09-03 20:33 UTC, veselcraft commented on Web/Presenters/templates/components/postChange.xml
> +</table>
![image](https://user-images.githubusercontent.com/22993408/188286810-a2036d4e-fad2-4302-b7b6-a756e7b851a6.png)
и алсо newline)

текущая версия бтв и так сверху есть

и ещё не хватает даты (если ты её конечно реализовывал)

2022-09-06 18:56 UTC, n1rwana commented on Web/Presenters/templates/components/postChange.xml
> +</table>
![image](https://user-images.githubusercontent.com/93197434/188716457-c57a32cc-aff3-4d0d-be7a-15505cfde0e7.png)

2023-06-16 07:46 UTC, WerySkok commented
Предлагаю вспомнить этот пр

2023-06-16 07:49 UTC, aqukie commented
Кстати, не только посты можно редактировать. Можно вспомнить про редактирование сообщений (хотя про них забыли все кто хочет)

2023-06-16 13:09 UTC, NoPlagiarism commented
> хотя про них забыли все кто хочет

#595

2023-08-11 16:23 UTC, lalka2016 commented
А что сейчас, после появления логов?

2023-09-22 22:24 UTC, WerySkok commented
унаследовано #979, которое уже мержнуто

2023-09-22 22:24 UTC, closed without merging