Fix of #667
OpenVK/openvk pull request #701
Opened 2022-08-28 21:14 UTC by n1rwana

Resolves #667

2022-08-28 21:15 UTC, veselcraft requested changes
а мб наоборот? чтобы проверка была в club.php, а не в user.php

2022-08-29 12:44 UTC, maksalees requested changes

2022-08-29 12:44 UTC, maksalees commented on Web/Presenters/templates/User/Groups.xml
> +        <form n:if="$x->isSubscribed($thisUser->getId())" class="profile_link_form" action="/setSub/club" method="post">
Проверять подписку на группу можно использую уже готовый метод `getSubscriptionStatus`. Также вместо полного скрытия кнопки, лучше отображать кнопку подписки. Просто скопируй код [отсюда](https://github.com/openvk/openvk/blob/master/Web/Presenters/templates/Group/View.xml#L108)

2022-08-29 12:44 UTC, maksalees commented on Web/Models/Entities/User.php
> -
Откуда это?

2022-08-29 15:21 UTC, n1rwana commented on Web/Models/Entities/User.php
> -
https://github.com/openvk/openvk/blob/d9ec6a169273ba744bd113ff9b4b7d4688a486b1/Web/Models/Entities/User.php#L1018

2022-08-29 15:27 UTC, maksalees requested changes

2022-08-29 15:27 UTC, maksalees commented on Web/Presenters/templates/User/Groups.xml
> +            <form action="/setSub/club" method="post">
```suggestion
            <form class="profile_link_form" action="/setSub/club" method="post">
```

2022-08-29 15:27 UTC, maksalees commented on Web/Presenters/templates/User/Groups.xml
> +            <form action="/setSub/club" method="post">
```suggestion
            <form class="profile_link_form" action="/setSub/club" method="post">
```

2022-08-29 15:27 UTC, maksalees commented on Web/Models/Entities/Club.php
> +    function isSubscribed(int $uid): bool
Этот метод теперь не нужен

2022-08-29 15:27 UTC, maksalees commented on Web/Models/Entities/User.php
> -
Всмысле откуда и зачем это изменение

2022-08-29 16:22 UTC, maksalees requested changes

2022-08-29 16:22 UTC, maksalees commented on Web/Presenters/templates/User/Groups.xml
> +            <form action="/setSub/club" method="post">
Вы не то сделали. Откатите ваше изменение и примините мое

2022-08-29 16:22 UTC, maksalees commented on Web/Presenters/templates/User/Groups.xml
> +            <form action="/setSub/club" method="post">
Вы не то сделали. Откатите ваше изменение и примините мое

2022-08-29 16:22 UTC, maksalees commented on Web/Models/Entities/User.php
> -
Уберите это изменение

2022-08-29 16:22 UTC, maksalees commented on Web/Models/Entities/Club.php
> -
Уберите это изменение

2022-09-03 20:15 UTC, veselcraft requested changes
куда-то спиздили newline и ещё классы забыл сделать

2022-09-03 20:15 UTC, veselcraft commented on Web/Models/Entities/Club.php
> -
newline нужен в конце файла

2022-09-03 20:15 UTC, veselcraft commented on Web/Models/Entities/User.php
> -
same

2022-09-03 20:15 UTC, veselcraft commented on Web/Presenters/templates/User/Groups.xml
> +            <form action="/setSub/club" method="post">
класс добавь (в комментах изменение)

2022-09-03 20:15 UTC, veselcraft commented on Web/Presenters/templates/User/Groups.xml
> +            <form action="/setSub/club" method="post">
same

2022-09-05 19:41 UTC, closed without merging