Модерация имён
OpenVK/openvk pull request #712
Opened 2022-09-05 15:24 UTC by n1rwana

Добавляет возможность включить модерацию имён. При её активации каждое изменение имени пользователем будет отправлено на модерацию.

![image](https://user-images.githubusercontent.com/93197434/188479641-b0a8ec82-1f7f-480c-882c-b109285b4045.png)

2022-09-05 15:41 UTC, AlesAlte commented
Я бы добавил возможность увеличить лимит с 250 на меньше или больше.
P.S У вас уже 8 открытых пуллов. Было бы хорошо, если бы вы доводили до конца...

2022-09-05 16:55 UTC, n1rwana commented
> Я бы добавил возможность увеличить лимит с 250 на меньше или больше.

Пока что это просто текст, скопированный из оригинального ВК. :)
![image](https://user-images.githubusercontent.com/93197434/188492107-896924dd-7df9-4517-a581-761f9ba0cccc.png)

2022-09-16 21:14 UTC, veselcraft requested changes
см. комменты + недопереводы есть в
`Web/Presenters/templates/Names/List.xml`
`Web/Presenters/templates/User/Edit.xml`

2022-09-16 21:14 UTC, veselcraft commented on Web/Presenters/templates/User/Settings.xml
> +
зач пробел

2022-09-16 21:14 UTC, veselcraft commented on data/knowledgebase/names.ru.md
> +* Новичкам, находящимся на испытательном сроке,<br>голоса впервые начисляются за <b>300</b> верно разобранных заявок.
советую убрать

2022-09-16 21:14 UTC, veselcraft commented on openvk-example.yml
> +        namesModeration: true
ну ето гуд

2025-08-02 14:05 UTC, veselcraft commented
лол забавная хуйня

2025-08-02 14:06 UTC, WerySkok commented
Нам лучше бы удалить этот функционал вовсе, чем добавлять его к себе

2025-08-16 13:12 UTC, closed without merging