Карточка Агента Поддержки
OpenVK/openvk pull request #717
Opened 2022-09-07 20:39 UTC by n1rwana

Добавляет карточку Агента Поддержки. Также стало проще редактировать "псевдонимы" Агентов (таблица `support_names`).

![image](https://user-images.githubusercontent.com/93197434/188972650-aa24db01-a72b-4981-9c1d-b8d460993717.png)
![image](https://user-images.githubusercontent.com/93197434/188972710-eb550053-f61e-4b0e-8ce0-19e3c8c0e703.png)

2022-09-07 20:39 UTC, n1rwana commented
Resolves #537

2022-09-08 07:30 UTC, AlesAlte commented
![зображення](https://user-images.githubusercontent.com/92401420/189061782-48d7065c-5de5-4ea3-a2b7-954323d7c341.png)
🙂

2022-09-08 07:43 UTC, n1rwana commented
🤔

2022-09-08 08:13 UTC, AlesAlte commented
> 🤔

Ждём, когда кое-какой энтузиаст начнёт комитить в музыку.

2022-09-16 21:18 UTC, veselcraft requested changes
есть некритичные приколы

2022-09-16 21:18 UTC, veselcraft commented on Web/Models/Entities/TicketComment.php
> +            return tr("helpdesk_agent") . " #" . $this->getAgentNumber();
не понял прикола замены `№` на `#`

2022-09-16 21:18 UTC, veselcraft commented on Web/Presenters/SupportPresenter.php
> +        ];
https://github.com/openvk/openvk/blob/master/CODE_STYLE.md#indentation

2022-09-16 21:18 UTC, veselcraft commented on Web/Presenters/templates/Support/Agent.xml
> +    Карточка агента
l18n

2022-09-16 21:18 UTC, veselcraft commented on Web/Presenters/templates/Support/Agent.xml
> +                <div>отрицательных ответов</div>
l18n

2022-09-16 21:18 UTC, veselcraft commented on Web/Presenters/templates/Support/Agent.xml
> +                <div>всего ответов</div>
l18n

2022-09-16 21:18 UTC, veselcraft commented on Web/Presenters/templates/Support/Agent.xml
> +                <label for="number">Аватар</label>
l18n

2022-09-16 21:18 UTC, veselcraft commented on Web/Presenters/templates/Support/Agent.xml
> +            <label for="number">Аватар</label>
l18n

2022-09-16 21:18 UTC, veselcraft commented on locales/ru.strings
> +"helpdesk_agent" = "Агент Поддержки";
newline отсутствует

2022-09-16 21:29 UTC, n1rwana commented on Web/Models/Entities/TicketComment.php
> +            return tr("helpdesk_agent") . " #" . $this->getAgentNumber();
В оригинальном ВК `#`

![image](https://user-images.githubusercontent.com/93197434/190780480-ac4fae4c-0be9-4c65-9a8f-21af9c0f8984.png)

2022-11-07 21:35 UTC, celestora commented
Я ненавижу этот раздел, поэтому даже проверять ничего не буду, хуже не станет точно, мы его уже достаточно покромсали всем коллективом.

2022-11-07 21:36 UTC, merged