Added other gender options
OpenVK/openvk pull request #718
Opened 2022-09-08 13:19 UTC by n1rwana

![image](https://user-images.githubusercontent.com/93197434/189132210-df4d61dd-6bd3-4320-92df-1e5c2e46e7e5.png)
![image](https://user-images.githubusercontent.com/93197434/189132387-5161b0ce-c8b8-48cf-a4e1-3f0d0dad2337.png)

Resolves #312

2022-09-08 13:32 UTC, el-psy-congroo-desu commented
Не вижу смысла в этом нововведении.

2022-09-08 13:33 UTC, n1rwana commented
Я лишь выполнил Issue #312  `¯\_(ツ)_/¯`

2022-09-08 13:36 UTC, el-psy-congroo-desu commented
> Я лишь выполнил Issue #312  `¯\_(ツ)_/¯`

Это конечно хорошо, но оригинальный вк даже не предлагает другой пол, кроме муж/жен.

2022-09-08 13:36 UTC, MatroCholo commented
@n1rwana Лишнее

2022-09-08 13:37 UTC, n1rwana commented
Ок.

2022-09-08 13:37 UTC, hetrixq commented
@n1rwana Сделай лучше музыку)))))))

2022-09-08 13:41 UTC, SuperErnD commented
> @n1rwana Сделай лучше музыку)))))))

согл

2022-09-08 13:41 UTC, SuperErnD commented
за голоса))

2022-09-08 13:56 UTC, AlesAlte commented
Идея имеет жизнь, но только если добавить "Небинарный" (без указания пола)

2022-10-13 09:08 UTC, n1rwana commented
Resolves #748

2022-12-11 22:45 UTC, NoPlagiarism commented
Если всё-таки собрались менять `sex` на `gender`. То как минимум, надо поменять ещё дефолтные fields в VKAPI

2024-10-31 10:26 UTC, ghost commented
бра

2024-10-31 10:38 UTC, celestora requested changes

2024-10-31 10:38 UTC, celestora commented on locales/en.strings
> +"other_gender_placeholder" = "I refer to myself as...";
identify as*

2024-10-31 10:38 UTC, celestora commented on VKAPI/Handlers/Users.php
> -								$response[$i]->sex = $usr->isFemale() ? 1 : 2;
мб оставить для совместимости? isFemale поменять на  `?bool` и возвращать `NULL`, если не кун и не тян

2024-10-31 10:38 UTC, celestora commented on .idea/deployment.xml
> +<?xml version="1.0" encoding="UTF-8"?>
ненужно

2025-08-16 13:12 UTC, closed without merging