Добавил соавторсто к одному комиту
OpenVK/openvk pull request #726
Opened 2022-09-12 17:59 UTC by Artem13327

Внимание! Я мог сломать  историю. Поэтому сделайте резервную копию истории
Вот если что Pull Request к которому нужно было добавить соавторство https://github.com/openvk/openvk/pull/716

2022-09-12 18:35 UTC, SuperErnD commented
reguest))

2022-09-12 20:23 UTC, n1rwana requested changes
https://github.com/openvk/openvk/pull/726/commits/e9d1ef20e76eb4b584a4be62fbc63335b98f0a15#diff-5b654ea86401547fdebf9a1d6f3bbaa75ea1ba572e755e256a11aa058f0ae412
https://github.com/openvk/openvk/pull/726/commits/e9d1ef20e76eb4b584a4be62fbc63335b98f0a15#diff-036da77e0e4b2f4e042049d9b20f5cfc4a347bc1e01391bd3bf3bc8ae4601768

Эти файлы не нужны. :)

2022-09-16 21:04 UTC, closed without merging

2023-02-23 19:34 UTC, Artem13327 commented
@n1rwana и мне щяс стало интересно. 
Зачем тогда Вы эти файлы добавили?

2023-02-24 06:25 UTC, NoPlagiarism commented
@Artem13327 ну, случайно были добавленны. Да и вообще в коммите https://github.com/openvk/openvk/commit/38e51a2b9d3d82622f19b816d20d6a544bd85495 они удалены.