Microblog docker
OpenVK/openvk pull request #76
Opened 2021-04-28 01:07 UTC by samuhin

Залил данную версию(microblog) OpenVk в Docker-контейнер, так как с более новой версией надо базу чинить немного и она динамически меняется. Так как установка содержит systemd, через докер надо запускать с ключом --privileged, в podman же без рута и без ключа можно.

Загрузил также к DockerHub:
docker run -it -p YOUR_PORT:80 --privileged samukhin/openvk:microblog

2021-04-28 06:12 UTC, veselcraft commented
оп оп оп живем живем
@rem-pai

2021-04-28 10:19 UTC, WerySkok commented on openvk-example.yml
> +                password: "DATABASE_PASSWORD"
возможно ли организовать рандомную генерацию паролей и ключей?

2021-04-28 17:41 UTC, samuhin commented on openvk-example.yml
> +                password: "DATABASE_PASSWORD"
Я работаю над этим, пока что там вообще без пароля, это для шаблона код
Главной целью была возможность развернуть данный проект одной командой без вагранта и не на freebsd. Так как "задолбался" его заводить каждый раз :)))))

2021-04-28 18:26 UTC, WerySkok commented on install/automated/common/autoexec
> +systemctl enable httpd
```suggestion
systemctl enable --now httpd
```
и убрать строку start

2021-04-30 03:07 UTC, samuhin commented
В общем, на текущий момент, версия microblog и в репозитории, и в dockerhub базово работает. Контейнер перезапускается, ничего само по себе не падает. Осталось сделать генерацию паролей.
Но я хотел бы сделать подобное для master ветки. Можно мне реально работающую базу, чистый дамп после первоначальной настройки? Я там, конечно, сам направил уже, но половина пунктов меню не работает)))))))

2021-04-30 03:39 UTC, samukhin commented
А, и ещё. Пофиксите мой ник в README (samuhin -> samukhin). Сейчас переименовался, для соответствия с dockerhub/gitlab, так как на момент создания аккаунта было занято.

2021-04-30 03:43 UTC, dsrev commented
Поправил.

Apr 30, 2021 10:39:19 AM samukhin ***@***.***>:

> А, и ещё. Пофиксите мой ник в README (samuhin -> samukhin). Сейчас переименовался, для соответствия с dockerhub/gitlab, так как на момент создания аккаунта было занято.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[https://github.com/openvk/openvk/pull/76#issuecomment-829783053], or unsubscribe[https://github.com/notifications/unsubscribe-auth/ANFN7EL2TLDLJ2Y7SGOVHP3TLIQ6NANCNFSM43WBTQVQ].
>  [data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEIAAABCCAYAAADjVADoAAAAAXNSR0IArs4c6QAAAARzQklUCAgICHwIZIgAAAAnSURBVHic7cEBDQAAAMKg909tDwcUAAAAAAAAAAAAAAAAAAAAAPBjRFIAASHKmKkAAAAASUVORK5CYII=###24x24:true###][Tracking image][https://github.com/notifications/beacon/ANFN7EI26KK4WDMI736NDJTTLIQ6NA5CNFSM43WBTQV2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOGF2XYDI.gif]
>

2021-04-30 03:44 UTC, dsrev commented
Лол, в моём клиенте электронной почты выглядело странно.
И да, поправил.

2021-04-30 03:46 UTC, samukhin commented
Базу рабочую можете выслать?

2021-05-03 12:29 UTC, samukhin commented
Сделал подобное для master-ветки

https://github.com/samukhin/openvk/tree/master
https://hub.docker.com/r/samukhin/openvk

2021-05-03 14:17 UTC, celestora requested changes

2021-05-03 14:17 UTC, celestora commented on install/automated/Docker|Podman/Dockerfile
>  FROM centos:8
А нет ли Docker образа для AlmaLinux?

2021-05-03 14:31 UTC, samukhin commented on install/automated/Docker|Podman/Dockerfile
>  FROM centos:8
Сначала бы этот до ума довести, но думаю с этим дистрибутивом проблем не возникнет.
Это же ведь логическое продолжение Centos? Надо смотреть что там в репозиториях
Ну и ещё, наверное, надо попробовать с debian-дистрибутивами

2021-05-03 15:50 UTC, samukhin commented
Сделал для AlmaLinux, полностью совместимые репозитории оказались

2021-05-03 18:27 UTC, celestora approved these changes

2021-05-03 18:30 UTC, celestora commented
Теперь было бы круто ещё если бы вы сделали это для ветки master и сделали новый PR в master. Тогда можно будет закрыть этот и смерджить новый.

2021-05-05 08:08 UTC, samukhin commented
Сделал + добавил сборку для федоры (там инструкций поменьше получилось и докер её чуть удачнее прожёвывает)
Однако всё ещё без генерации паролей

2021-09-20 14:00 UTC, closed without merging