VKAPI: new method account.saveProfileInfo (again)
OpenVK/openvk pull request #775
Opened 2022-11-06 14:51 UTC by vlapsk1y

A little bit dumb. Review asap.

2022-11-06 15:04 UTC, celestora requested changes

2022-11-06 15:04 UTC, celestora commented on VKAPI/Handlers/Account.php
> +        if ($first_name != "" || $last_name != "")
`empty()` над

2022-11-06 15:04 UTC, celestora commented on VKAPI/Handlers/Account.php
> +        if ($first_name != "" || $last_name != "")
пробелы после if/for/while у нас делать не принято

2022-11-06 15:04 UTC, celestora commented on VKAPI/Handlers/Account.php
> +            $output["name_request"] = [
где `{`? это будет работать, но убирать скобки такие желательно тогда, когда внизу либо безскобычный оператор либо что-то что поместится в одну строчку.

https://github.com/openvk/openvk/blob/master/CODE_STYLE.md#usage-of-curly-braces

2022-11-06 15:04 UTC, celestora commented on VKAPI/Handlers/Account.php
> +                "last_name" => ($last_name != "") ? $last_name : $this->getUser()->getLastName(),
`empty`

2022-11-06 15:04 UTC, celestora commented on VKAPI/Handlers/Account.php
> +        if ($first_name != "")
empty + скобки

2022-11-06 15:04 UTC, celestora commented on VKAPI/Handlers/Account.php
> +            try {
у меня вообще вопрос а не логичнее ли всю эту логику запихнуть в один try/catch?

2022-11-06 15:04 UTC, celestora commented on VKAPI/Handlers/Account.php
> +            if ($sex == 2)
это будет распарсено как

```php
if ($sex > -1 && $sex == 1)
  $this->getUser()->setSex(0);
if ($sex == 2)
  $this->getUser()->setSex(1);
```

Я не знаю насколько это плохо в данном случае но ладно

2022-11-06 15:04 UTC, celestora commented on VKAPI/Handlers/Account.php
> +        if ($bdate != "")
empty :D

2022-11-06 15:04 UTC, celestora commented on VKAPI/Handlers/Account.php
> +                $this->getUser()->setBirthday_privacy(0);
тот же доёб к скобкам

2022-11-06 15:04 UTC, celestora commented on VKAPI/Handlers/Account.php
> +        }
пиздец

2022-11-06 18:37 UTC, vlapsk1y reviewed
fix

2022-11-06 19:40 UTC, celestora requested changes
некоторые доёбы по кодстайлу

2022-11-06 19:40 UTC, celestora commented on VKAPI/Handlers/Account.php
>              $this->getUser()->setBirthday(strtotime($bdate));
что будет если `strtotime` провалится?

2022-11-06 19:40 UTC, celestora commented on VKAPI/Handlers/Account.php
> +        if($sex > 0) {
а зач эти условия вообще?

2022-11-06 19:40 UTC, celestora commented on VKAPI/Handlers/Account.php
> +                "last_name" => (!empty($last_name)) ? $last_name : $this->getUser()->getLastName(),
лишние скобы

2022-11-06 19:40 UTC, celestora commented on VKAPI/Handlers/Account.php
> +        if(!empty($first_name) || !empty($last_name) || !empty($screen_name) || $sex > 0 || $relation > -1 || !empty($bdate) || $bdate_visibility >= 1 || !empty($home_town) || !empty($status)) {
`if($sex > 0 || $relation > -1 || $bdate_visibility > 1 || !empty("$first_name$last_name$screen_name$bdate$home_town$status"))`

2022-11-07 14:22 UTC, vlapsk1y commented on VKAPI/Handlers/Account.php
> +        if($sex > 0) {
потому что (https://dev.vk.com/method/account.saveProfileInfo)
<img width="555" alt="Снимок экрана 2022-11-07 в 19 21 51" src="https://user-images.githubusercontent.com/94683384/200333373-df1ed5f2-4629-4a16-9390-91dd2656d0cf.png">

2022-11-07 21:25 UTC, celestora requested changes
некоторые доёбы по код-стайлу

2022-11-07 21:25 UTC, celestora commented on VKAPI/Handlers/Account.php
>              $this->getUser()->setBirthday(strtotime($bdate));
`strtotime` вызывается дважды, потеря вычислительных циклов

2022-11-07 21:25 UTC, celestora commented on VKAPI/Handlers/Account.php
> +        if(!empty($bdate) && strtotime($bdate) < time())
`$bdate` - переменная из космоса (от юзера, мы не контроллируем её контент). `strtotime` в случае некорректных данных возвращает `false`. Предположим, что `$bdate` не содержит дату, в таком случае условие почти всегда равно `true`: false < (int) будет false только для (int) = 0, что очень маловероятно. И того мы имеем следующее: в случае если кирилл заволожин засабмитит в bdate "cock and balls torture", в setBirthday попадёт false, что вызовет TypeError и ошибку писот. Конкретно здесь это максимум в перспективе родит багрепорт, на который всем будет посрать, однако лучше всегда *очень осторожно* относиться к данным которые пришли из жопы, а пользователи веб-приложений это всегда жопа. ~Даже если они не русские.~\
Настоятельно рекоммендую добавить проверку на ошибки `strtotime`.

2022-11-07 21:25 UTC, celestora commented on VKAPI/Handlers/Account.php
>          if($bdate_visibility >= 1) {
Для $bdate_visibility ∈ [1, 2] всегда выполняется `$bdate_visibility >= 1`, зачем тут это условие? Вы хотели что-то сделать в случае, если оно таки меньше 1? Или вы ожидали, что может быть такое, что `$bdate_visibility == 2` будет истинным, а `$bdate_visibility >= 1` при этом ложным?)

2022-11-07 21:25 UTC, celestora commented on VKAPI/Handlers/Account.php
> +            } catch (\Exception $e) {
Я допускаю, что возможны смешные ситуации, когда setLast_Name выбросят исключение, которое отличается от тех, которые вы ожидаете словить. Какие последствия будут, если вы будете ловить их через `\Exception`? Опять-таки, конкретно тут доёб больше к код-стайлу, но такой код может скрыть какой-нибудь интересный багос.

2022-11-07 21:25 UTC, celestora commented on VKAPI/Handlers/Account.php
>                  "id" => 1, # Заглушка
Я бы взял `random_int(1, 2048)` для какой-никакой совместимости с некоторыми клиентами VK,

2022-11-07 21:25 UTC, celestora commented on VKAPI/Handlers/Account.php
> +                    $this->getUser()->setLast_Name($last_name);
Что-то часто тут `$this->getUser()`. И лишний вызов и лишние буквы, мб вынести в переменную?

2022-11-07 21:25 UTC, celestora commented on VKAPI/Handlers/Account.php
> +                "last_name" => !empty($last_name) ? $last_name : $this->getUser()->getLastName(),
(доёб с нихуя)

2022-11-08 14:11 UTC, celestora requested changes
некоторые доёбы остались

2022-11-08 14:11 UTC, celestora commented on VKAPI/Handlers/Account.php
>                  "id" => 1, # Заглушка
мяу?

2022-11-08 14:11 UTC, celestora commented on VKAPI/Handlers/Account.php
> +            } catch (\Exception $e) {
мяу?

2022-11-08 14:11 UTC, celestora commented on VKAPI/Handlers/Account.php
> +        if($bdate_visibility > 0) {
доёб был не про это но я понял прикол

2022-11-08 14:11 UTC, celestora commented on VKAPI/Handlers/Account.php
> +            $this->getUser()->setBirthday($birthday);
`$user`?

2022-11-08 14:11 UTC, celestora commented on VKAPI/Handlers/Account.php
>              $this->getUser()->setMarital_Status($relation);
`$user`?

2022-11-09 19:38 UTC, closed without merging