VKAPI: new method account.saveProfileInfo (again)
OpenVK/openvk pull request #777
Opened 2022-11-09 19:44 UTC by vlapsk1y

Случайно закрыл предыдущий пр когда обновлял форк. асап плиз

2022-11-09 19:57 UTC, celestora requested changes
Есть некоторые доёбы к код-стайлу

2022-11-09 19:57 UTC, celestora commented on VKAPI/Handlers/Account.php
> +                $this->fail(946, "Don't show date of birth is not implemented.");
Don't show = hiding

2022-11-09 19:57 UTC, celestora commented on VKAPI/Handlers/Account.php
> +        if($sex > 0) {
интересно почему не `$user->setSex($sex == 1 ? 1 : 0)`

2022-11-10 11:47 UTC, celestora approved these changes
норм

2022-11-10 11:47 UTC, celestora commented on VKAPI/Handlers/Account.php
> +        if($sex > 0)
так а нахуя это `$sex > 0` я так и не понял, но ладно

2022-11-10 13:27 UTC, celestora commented
так и не объяснил нихуя про $sex > 0

2022-11-10 13:27 UTC, merged

2022-11-10 13:48 UTC, vlapskii commented
> так и не объяснил нихуя про $sex > 0

Если в профиле будет указан пол женский (в овк это значение: 1), и когда будет запрос к данному методу, так как по дефолту там значение -1 стоит, т.е. это не будет тождественно 1 в тернарном операторе ($sex == 1 ? 1 : 0), то после обращение к данному методу пол в профиле поменяется на мужской, даже если этот параметр не задействован в запросе, поэтому и стоит проверка.