Разные class для floating_sidebar
OpenVK/openvk pull request #787
Opened 2022-11-21 20:24 UTC by ZAZiOs

Если хочется при создании темы заменить иконки у уменьшенного сайд-бара то это сделать не выйдет. Данный фикс называет классы иконок по разному, чтобы можно было поменять каждую.

2022-11-21 22:44 UTC, maksalees requested changes

2022-11-21 22:44 UTC, maksalees commented on Web/Presenters/templates/@layout.xml
> +                                <a class="minilink-friends" href="/friends{$thisUser->getId()}">
Так как к классу `minilink` в CSS приминены стили, этот фикс все сломает. Вместо замены класса на отдельный, оставь обычный класс `minilink`. Вот так:
```suggestion
                                <a class="minilink minilink-friends" href="/friends{$thisUser->getId()}">
```

2022-11-22 04:21 UTC, ZAZiOs commented on Web/Presenters/templates/@layout.xml
> +                                <a class="minilink-friends" href="/friends{$thisUser->getId()}">
Обновил для каждого класса, ожидаю рассмотрения

2022-11-22 19:11 UTC, maksalees approved these changes

2022-11-22 19:21 UTC, maksalees requested changes

2022-11-22 19:21 UTC, maksalees commented on Web/Presenters/templates/@layout.xml
> +                                <a class="minilink minilink-friends" href="/friends{$thisUser->getId()}">
Хотя вообще как мне кажется, лучше сделать не разные классы, а ID
```suggestion
                                <a id="minilink-friends" class="minilink" href="/friends{$thisUser->getId()}">
```

2022-11-22 19:51 UTC, ZAZiOs commented on Web/Presenters/templates/@layout.xml
> +                                <a class="minilink minilink-friends" href="/friends{$thisUser->getId()}">
Окей, заменил на id

2022-11-24 21:32 UTC, maksalees approved these changes

2022-11-25 04:59 UTC, closed without merging