Страница регистрации из 2007г
OpenVK/openvk pull request #788
Opened 2022-11-22 19:08 UTC by ZAZiOs

Обновил страницу регистрации по запросу @myslivets 
До:
![image](https://user-images.githubusercontent.com/85897688/203400314-9ea617dc-14f0-4c49-9218-1807419157e0.png)
После:
![image](https://user-images.githubusercontent.com/85897688/203400425-877b172b-0f21-4ca8-8fa9-da21bcd9ce63.png)
![image](https://user-images.githubusercontent.com/85897688/203400468-484c53a1-c680-454a-8357-21bca89df6f6.png)

(и добавление названий классов, оно просто с моего форка подтянулось, я не знал как убрать эти коммиты ¯\\_(ツ)_/¯ )

2022-11-22 19:11 UTC, maksalees requested changes
Есть немного придирок

2022-11-22 19:11 UTC, maksalees commented on Web/Presenters/templates/@layout.xml
> +                                <a class="minilink minilink-friends" href="/friends{$thisUser->getId()}">
А это здесь зачем?

2022-11-22 19:11 UTC, maksalees commented on Web/Presenters/templates/Auth/Login.xml
> +					<center>
Что с форматированием

2022-11-22 19:11 UTC, maksalees commented on Web/Presenters/templates/Auth/Register.xml
> +		<div style="margin: 10px;">
Что с форматированием

2022-11-22 19:11 UTC, maksalees commented on Web/Presenters/templates/Auth/Register.xml
> +		<b>OpenVK - универсальное средство поиска коллег основанное на структуре ВКонтакте.</b>
Лучше переведите и замените "OpenVK" на название инстанса

2022-11-22 19:11 UTC, maksalees commented on Web/static/css/style.css
> +h2 {
Что вы хотели здесь сделать? Это применит изменения на весь OpenVK

2022-11-22 19:12 UTC, ZAZiOs commented on Web/static/css/style.css
> +h2 {
Я добавил заголовок типа h2. До этого он был просто чёрным. Теперь - выше показано на месте "Регистрация"

2022-11-22 19:13 UTC, myslivets commented on Web/Presenters/templates/@layout.xml
> +                                <a class="minilink minilink-friends" href="/friends{$thisUser->getId()}">
походу это из-за #787

2022-11-22 19:13 UTC, ZAZiOs commented on Web/Presenters/templates/Auth/Register.xml
> +		<div style="margin: 10px;">
Мысливец попросил добавить доп. отступы вокруг страницы регистрации. Могу в лс в телеграме прислать скриншот по которому я делал.

2022-11-22 19:14 UTC, maksalees commented on Web/Presenters/templates/Auth/Register.xml
> +		<div style="margin: 10px;">
> Мысливец попросил добавить доп. отступы вокруг страницы регистрации. Могу в лс в телеграме прислать скриншот по которому я делал.

Я имел ввиду форматирование кода

2022-11-22 19:14 UTC, ZAZiOs commented on Web/Presenters/templates/@layout.xml
> +                                <a class="minilink minilink-friends" href="/friends{$thisUser->getId()}">
Я создавал пулл реквест из своего форка, гитхабом ещё пока-что слабо умею пользоваться, не нашёл как откинуть данные коммиты.

2022-11-22 19:16 UTC, maksalees commented on Web/static/css/style.css
> +h2 {
Но это изменит внешний вид заголовка во многих местах OpenVK, таких как страница. Лучше сделай это отдельным классом.

2022-11-22 19:16 UTC, ZAZiOs commented on Web/Presenters/templates/Auth/Login.xml
> +					<center>
Требуется для выравнивания кнопок и надписи "Забыл пароль?" под полями входа. Не вышло сделать это используя css.

2022-11-22 19:23 UTC, maksalees commented on Web/Presenters/templates/Auth/Login.xml
> +					<center>
Я имел ввиду форматирование кода

2022-11-22 19:25 UTC, myslivets commented
Вместо "Имя" можно ещё написать как "Основная информация"
![изображение](https://user-images.githubusercontent.com/60743585/203403731-87114814-b358-4835-9a91-bd6dc9aa18cb.png)

2022-11-22 19:35 UTC, veselcraft commented
> Вместо "Имя" в полоске можно ещё написать как "Основная информация" ![изображение](https://user-images.githubusercontent.com/60743585/203403731-87114814-b358-4835-9a91-bd6dc9aa18cb.png)

{_main}

2022-11-22 19:41 UTC, ZAZiOs commented
> > Вместо "Имя" в полоске можно ещё написать как "Основная информация" ![изображение](https://user-images.githubusercontent.com/60743585/203403731-87114814-b358-4835-9a91-bd6dc9aa18cb.png)
> 
> {_main}

Обновил 
![image](https://user-images.githubusercontent.com/85897688/203406372-b52b1327-83a0-41fe-8398-3479c9ce9e70.png)

2022-11-22 19:49 UTC, celestora commented
Приятно смотреть на то как страницы-заглушки обретают свой дизайн. Всё как Кичулкин завещал.

2022-11-22 19:52 UTC, veselcraft commented
хотелось бы ещё чтоб дефолт значок можно было поменять  
![image](https://user-images.githubusercontent.com/22993408/203408422-2857e4da-7d42-40e3-86ad-cf68f1d5c262.png)
 вот здесь которое

2022-11-22 19:54 UTC, ZAZiOs commented
> хотелось бы ещё чтоб дефолт значок можно было поменять ![image](https://user-images.githubusercontent.com/22993408/203408422-2857e4da-7d42-40e3-86ad-cf68f1d5c262.png) вот здесь которое

Иконка здесь находится по адресу Web\static\img\favicons\favicon64.png
Я думаю что если человеку понадобится заменить все иконки на иконки своего инстанса, то он заменит эти файлы

2022-11-22 20:07 UTC, ZAZiOs commented
Требуется помощь с сообщением здесь
![image](https://user-images.githubusercontent.com/85897688/203410582-af6eef67-ce6e-410e-ab49-647451d83456.png)
Что с ним делать? Сейчас в код вставлен именно текст, никаких локалей(Возможно следует прописать это сообщение в locales) Также не получается заменить название инстанса, если оно не OpenVK. При попытке использования {$instance_name} на сайте просто пропадает название инстанса.
![image](https://user-images.githubusercontent.com/85897688/203411062-abbac301-9f96-47ba-988e-012a9930d76c.png)

2022-11-22 20:46 UTC, saursvepur commented
> Требуется помощь с сообщением здесь Что с ним делать? Сейчас в коде вставлен именно текст, никаких локалей(Возможно следует прописать это сообщение в локалях) Также не получается сделать измененное название инстанса. При рекомендуемом использовании {$instance_name} на сайте просто пропадает название инстанса. ![изображение](https://user-images.githubusercontent.com/85897688/203410582-af6eef67-ce6e-410e-ab49-647451d83456.png) ![изображение](https://user-images.githubusercontent.com/85897688/203411062-abbac301-9f96-47ba-988e-012a9930d76c.png)

$1 попробуй

2022-11-22 21:09 UTC, veselcraft commented
> > хотелось бы ещё чтоб дефолт значок можно было поменять ![image](https://user-images.githubusercontent.com/22993408/203408422-2857e4da-7d42-40e3-86ad-cf68f1d5c262.png) вот здесь которое
> 
> Иконка здесь находится по адресу Web\static\img\favicons\favicon64.png Я думаю что если человеку понадобится заменить все иконки на иконки своего инстанса, то он заменит эти файлы

а конфиг

2022-11-22 21:09 UTC, veselcraft commented
> Требуется помощь с сообщением здесь ![image](https://user-images.githubusercontent.com/85897688/203410582-af6eef67-ce6e-410e-ab49-647451d83456.png) Что с ним делать? Сейчас в код вставлен именно текст, никаких локалей(Возможно следует прописать это сообщение в locales) Также не получается сделать адаптированное название инстанса. При попытке использования {$instance_name} на сайте просто пропадает название инстанса. ![image](https://user-images.githubusercontent.com/85897688/203411062-abbac301-9f96-47ba-988e-012a9930d76c.png)

```
{php echo OPENVK_ROOT_CONF['openvk']['appearance']['name']}
```

2022-11-22 22:18 UTC, ZAZiOs commented
Все замечания были приняты к сведению и исправлены. Прошу пересмотреть пулл.

2022-11-22 22:22 UTC, celestora requested changes

2022-11-22 22:22 UTC, celestora commented on Web/Presenters/templates/Auth/Register.xml
> +	                <img src="assets/packages/static/openvk/img/favicons/favicon64.png" style="width: 32px;" align="middle"></img>
што тут случилос с img

2022-11-22 22:22 UTC, celestora commented on Web/Presenters/templates/Auth/Register.xml
> +		        <h4 style="margin-left: 60px;">{_main}</h4>
h4 должнг быть в отдельном tr. позиция того что есть сейчас - неопределённое поведение.

2022-11-22 22:22 UTC, celestora commented on Web/Presenters/templates/Auth/Register.xml
> +					<tr>
пепяка с табами

2022-11-22 22:22 UTC, celestora commented on Web/Presenters/templates/Auth/Register.xml
> +					<tr>
пепяка с табами

2022-11-22 22:22 UTC, celestora commented on Web/Presenters/templates/Auth/Register.xml
> +                        <td style="text-align: right;">
хммм, мб вынести в CSS? на табличку айди regform повесить или чёт такое

2022-11-23 19:35 UTC, ZAZiOs commented
Исправлено всё что было предложено @celestora
Также обновлены страницы восстановления доступа
![image](https://user-images.githubusercontent.com/85897688/203632143-bcbffab6-613c-4639-adc2-ae0541a3023b.png)
![image](https://user-images.githubusercontent.com/85897688/203632225-b22cd01e-c797-4a8b-96c3-92b859aec78f.png)
Пункта о двухфакторном входе после основной авторизации
![image](https://user-images.githubusercontent.com/85897688/203632316-dff907a0-bc47-4817-914d-61c129030b6c.png)

2022-12-06 10:04 UTC, veselcraft commented
@celestora @maksalees

2022-12-09 15:58 UTC, celestora approved these changes
более менее

2023-01-07 19:52 UTC, merged