Проверка на надежный пароль
OpenVK/openvk pull request #862
Opened 2023-04-02 23:36 UTC by lokot0k

Возможность на инстансе указывать только надежный пароль при регистрации

2023-04-17 10:00 UTC, WerySkok commented on locales/ru.strings
> +"error_weak_password" = "Ненадежный пароль. Пароль должен содержать не менее 8-ми символов, в том числе цифры, прописаные и строчные буквы";
```suggestion
"error_weak_password" = "Ненадежный пароль. Пароль должен содержать не менее 8-ми символов, в том числе цифры, прописные и строчные буквы";
```

2023-04-19 08:15 UTC, veselcraft requested changes
код good, есть претензия к локали, а так готов принять

2023-04-19 08:15 UTC, veselcraft commented on locales/ru.strings
> +"error_weak_password" = "Ненадёжный пароль. Пароль должен содержать не менее 8-ми символов, в том числе цифры, прописные и строчные буквы";
"в том числе" лучше убрать

2023-04-19 08:21 UTC, ayaaop commented on locales/ru.strings
> +"error_weak_password" = "Ненадёжный пароль. Пароль должен содержать не менее 8-ми символов, в том числе цифры, прописные и строчные буквы";
8_-ми_ символов
-ми необязательно

2023-04-19 10:54 UTC, lokot0k commented on locales/ru.strings
> +"error_weak_password" = "Ненадёжный пароль. Пароль должен содержать не менее 8-ми символов, в том числе цифры, прописные и строчные буквы";
поправил

2023-04-19 11:02 UTC, merged

2023-04-20 04:04 UTC, tretdm commented
Исправил синтаксическую ошибку в английской локализации https://github.com/openvk/openvk/commit/252ff0ead06fcd018c4cb7b02ed0d857bbd12e9c, ибо вы забыли символ `;` в конце вставить)))0).