Add Utils.resolveScreenName
OpenVK/openvk pull request #884
Opened 2023-06-01 16:40 UTC by NoPlagiarism

`вк стандартизировано`

Как и поведение с `id1231312321321312` и `club123312313`, чтобы не запрашивать каждую подобную фигню

Код был написан так же, как и пишут глупые роботы. Оно должно работать

2023-06-01 17:12 UTC, celestora requested changes
ya vspomnil pro codestyl

2023-06-01 17:12 UTC, celestora commented on VKAPI/Handlers/Utils.php
> +                    "object_id" => intval(substr($screen_name, strlen("id"))),
intval bruh moment numero quatro https://github.com/openvk/openvk/blob/master/CODE_STYLE.md#casts

2023-06-01 17:12 UTC, celestora commented on VKAPI/Handlers/Utils.php
> +        if (\Chandler\MVC\Routing\Router::i()->getMatchingRoute("/$screen_name")[0]->presenter !== "UnknownTextRouteStrategy") {
https://github.com/openvk/openvk/blob/master/CODE_STYLE.md#tabspace

2023-06-01 17:12 UTC, celestora commented on VKAPI/Handlers/Utils.php
> +            if (!$alias) return (object)[];
https://github.com/openvk/openvk/blob/master/CODE_STYLE.md#blank-lines

2023-06-01 17:15 UTC, NoPlagiarism commented
В принципе, этого стоило ожидать
Спасибо за замечание

2023-06-02 21:37 UTC, merged

2023-06-02 21:37 UTC, veselcraft commented
ой блять я чет не заметил wip в названии

2023-06-02 21:37 UTC, veselcraft commented
ну тогда надо было пулл реквест драфтом назвать не знаю

2023-06-02 21:37 UTC, veselcraft commented
короче ладно если оно не будет работать мы тебя позовём

2023-06-03 06:41 UTC, NoPlagiarism commented
> оно не будет работать мы тебя позовём

аххаха, да оно должно работать

Просто хотел, чтобы хоть два человека понимающих глянуло на код

2023-06-03 08:03 UTC, NoPlagiarism commented
Можете не звать. Я уже в фулл дибилоиде

2023-06-03 08:13 UTC, NoPlagiarism commented
А может и не зря WIP стояло. 

- [x] `id12312321` 
- [x] `club1232131212`
- [ ] `va11halla` - не работает

2023-06-03 08:17 UTC, NoPlagiarism commented
Я так понял, что все shortcodes не были перенесены в `Aliases`?