New localization strings for OpenVK Mobile web theme
OpenVK/openvk pull request #897
Opened 2023-06-12 05:54 UTC by tretdm

Это, кстати, необходимо для перевода менюшки из мобильной темы веб-версии OpenVK.
https://github.com/openvk/mobile_ovk/issues/5

2023-06-12 06:04 UTC, aqukie approved these changes

2023-06-12 06:04 UTC, aqukie commented on locales/uk.strings
> +"menu_settings" = "Налаштування";
![image](https://github.com/openvk/openvk/assets/124827134/86147fc2-5d2f-4fc5-a87a-9f43e3c200bf)
Зачем придумывать новые строки, когда они уже есть?

2023-06-12 06:07 UTC, tretdm commented on locales/uk.strings
> +"menu_settings" = "Налаштування";
Но прикол только в том, что в самом меню темы нет слова "Мой", "My" и т. п.

2023-06-12 06:08 UTC, tretdm commented on locales/uk.strings
> +"menu_settings" = "Налаштування";
![изображение](https://github.com/openvk/openvk/assets/76806170/a9710aa4-71d1-43d8-8dc1-9fe664240056)
Я щас серьезно.

2023-06-12 06:15 UTC, aqukie commented
Да и в общем, локализация касается только веб версии OpenVK, а не темы, поэтому это стоит как-то отделить

2023-06-12 06:19 UTC, tretdm commented
> Да и в общем, локализация касается только веб версии OpenVK, а не темы, поэтому это стоит как-то отделить

Только вот над отдельным переводом для конкретной темы тупо не заморачивались. Честно, я не видел, чтобы хотя бы одна из тем имела свою локаль? максимум свои макеты были.

2023-06-13 17:54 UTC, veselcraft requested changes
размести связанные с мобилками строки в отдельную категорию плиз

типа так
```strings
/* Mobile */
"mobile_tits" = "сиськи ⚡";
```

2023-06-14 08:43 UTC, tretdm commented
ща потом допилю))))

2023-06-14 08:53 UTC, tretdm commented
Все, чекайте.

2023-06-14 09:06 UTC, tretdm commented
Добавил еще пару недостающих строк.

2023-06-15 09:15 UTC, veselcraft approved these changes

2023-06-15 09:15 UTC, merged

2023-06-15 09:17 UTC, veselcraft commented
жду пулл реквеста в https://github.com/openvk/mobile_ovk