Возможность пользователю закрывать тикет
OpenVK/openvk pull request #925
Opened 2023-07-20 13:57 UTC by n1rwana

Этот PR добавляет возможность пользователям закрывать тикеты в Поддержке, если на них ответил агент.
Resolves #879 

![image](https://github.com/openvk/openvk/assets/93197434/41709ca0-0579-49a5-9321-00bfe31d9aaa)

2023-07-20 15:43 UTC, tretdm requested changes

2023-07-20 15:43 UTC, tretdm commented on Web/Presenters/templates/Support/View.xml
Эти строки (это №47) можно было перевести хотя бы на английский и украинские языки.

2023-07-20 15:43 UTC, tretdm commented on Web/Presenters/SupportPresenter.php
Аналогично в №396 - там недопереведены строки "Успех" и "Профиль создан. Теперь пользователи видят Ваши псевдоним и аватарку вместо стандартных аватарки и номера."

2023-07-28 08:27 UTC, tretdm approved these changes

2023-07-30 08:05 UTC, veselcraft requested changes, later dismissed

2023-07-30 08:05 UTC, veselcraft commented on Web/Presenters/templates/Support/View.xml
> +                error: () => alert("Произошла ошибка"),
перевод

2023-08-09 12:41 UTC, WerySkok commented
@veselcraft проверь пжпжпжппж

2023-08-09 12:44 UTC, veselcraft commented
https://github.com/openvk/openvk/assets/22993408/1a5b361d-c879-4d0a-9d7c-52d162c1fe14

2023-08-10 23:11 UTC, merged