[Wall] Список лайкнувших и поделившихся записью/комментарием
OpenVK/openvk pull request #968
Opened 2023-08-15 08:53 UTC by n1rwana

Resolves #31 
![image](https://github.com/openvk/openvk/assets/93197434/db7c9e84-e675-4a23-b6c2-57347310c9ec)

2023-08-15 09:22 UTC, lalka2016 commented
Лучше сделать всплывающую подсказку на tippy js (в сером цвете конечно)
![и](https://github.com/openvk/openvk/assets/99399973/05013514-9dd3-4196-ab0d-0a4f5255127b)
![з](https://github.com/openvk/openvk/assets/99399973/0b3d5fe2-2d5f-4579-a6f1-3f719e4f75d6)

2023-08-25 22:15 UTC, veselcraft commented
ждём всем чатом всплывашку как в ориг вк :D

2023-10-03 18:24 UTC, damirap2020 commented
ну че когда

2023-10-03 18:32 UTC, WerySkok commented
Там мерж конфликт

2023-10-03 18:36 UTC, SuperErnD commented
> ну че когда

через 5 лет, 6 месяцев, 17 дней, 13 часов, 56 минут, 51 секунду

2023-11-14 19:48 UTC, WerySkok requested changes
Советую решить конфликт слияния

2024-06-26 20:16 UTC, kekson1a commented
Кстати да а будет ли это продолжаться

2024-11-01 11:01 UTC, veselcraft commented
не знаю

2024-12-09 15:49 UTC, ghost commented
Уже добавлено, правда без репостов

2024-12-09 15:49 UTC, closed without merging